#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)"

LC_ALL=C.UTF-8 shellcheck "$@" \
    CI-Examples/bash/scripts/bash_test.sh \
    CI-Examples/common_tools/benchmark-http.sh \
    CI-Examples/python/run-tests.sh \
    tools/gramine.in \
    Scripts/clean-check \
    Scripts/clean-check-prepare \
    Scripts/clean-check-test-copy \
    Scripts/download \
    Scripts/gitignore-test \
    .ci/run-pylint \
    .ci/run-shellcheck
