name: 'Run Orca Python Jep Exampletest Py37'
description: 'Run Orca Python Jep Exampletest Py37'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install wget

    - name: Setup env
      shell: bash
      run: |
        if conda info --env | grep "py37"; then
            source activate py37
        else
            conda create -n py37 -y python==3.7.10 setuptools==58.0.4 -c ${CONDA_CHANNEL} --override-channels
            conda info --env
            source activate py37
        fi

        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        wget https://raw.githubusercontent.com/analytics-zoo/BigDL/main/python/test/python-requirements/requirements-orca-python-jep.txt -O ${{ github.workspace }}/requirements-orca-python-jep.txt
        pip uninstall -r ${{ github.workspace }}/requirements-orca-python-jep.txt -y
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca
        pip install -i ${PIP_MIRROR} --trusted-host ${TRUSTED_HOST} -r ${{ github.workspace }}/requirements-orca-python-jep.txt
        pip uninstall -y opencv-python-headless
        pip install opencv-python-headless
        
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
