name: 'Run Colab Python Py37 tf1'
description: 'Run Colab Python Py37 tf1'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Install dependencies
      shell: bash
      run: |
        dpkg --configure -a
        apt-get update
        apt-get install -y zip
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

    - name: Setup env
      shell: bash
      run: |
        if [ -d "/opt/conda/envs/py37" ];then
          rm -rf /opt/conda/envs/py37
        fi
        conda create -n py37 -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        source activate py37
        pip install wheel
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        wget https://raw.githubusercontent.com/analytics-zoo/gha-cicd-env/main/python-requirements/requirements-colab-python-tf1-spark3.txt -O ${{ github.workspace }}/requirements-colab-python-tf1-spark3.txt
        pip uninstall -r ${{ github.workspace }}/requirements-colab-python-tf1-spark3.txt -y
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r ${{ github.workspace }}/requirements-colab-python-tf1-spark3.txt

      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
    
    - name: Run test
      shell: bash
      run: |
        set -x
        set -e
        export CLASSPATH=.:${JAVA_HOME}/lib:${JAVA_HOME}/jre/lib:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/lib/dt.jar
        export PATH=${JAVA_HOME}/bin/:${JAVA_HOME}/jre/bin:${PATH}
        export PATH=/opt/hostedtoolcache/maven/3.6.3/x64:$PATH 
        export SPARK_LOCAL_HOSTNAME=localhost
        source activate py37
        chmod a+x python/orca/dev/colab-notebook/ipynb2py.sh
        chmod a+x python/orca/dev/colab-notebook/run-notebook-tf1.sh
        pip uninstall -y bigdl bigdl-dllib bigdl-orca 
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca
        pip install jupyter
        bash python/orca/dev/colab-notebook/run-notebook-tf1.sh
        source deactivate

      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_HOME: ${{ github.workspace }}