// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/resources/serialization/serialization.proto

package serialization;

public final class Serialization {
  private Serialization() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(serialization.Serialization.customizedData);
  }
  public interface TestParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.TestParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double scalar = 1;</code>
     */
    boolean hasScalar();
    /**
     * <code>required double scalar = 1;</code>
     */
    double getScalar();
  }
  /**
   * Protobuf type {@code serialization.TestParam}
   */
  public static final class TestParam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.TestParam)
      TestParamOrBuilder {
    // Use TestParam.newBuilder() to construct.
    private TestParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestParam(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestParam defaultInstance;
    public static TestParam getDefaultInstance() {
      return defaultInstance;
    }

    public TestParam getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              scalar_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serialization.Serialization.internal_static_serialization_TestParam_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serialization.Serialization.internal_static_serialization_TestParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serialization.Serialization.TestParam.class, serialization.Serialization.TestParam.Builder.class);
    }

    public static com.google.protobuf.Parser<TestParam> PARSER =
        new com.google.protobuf.AbstractParser<TestParam>() {
      public TestParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestParam(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestParam> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SCALAR_FIELD_NUMBER = 1;
    private double scalar_;
    /**
     * <code>required double scalar = 1;</code>
     */
    public boolean hasScalar() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double scalar = 1;</code>
     */
    public double getScalar() {
      return scalar_;
    }

    private void initFields() {
      scalar_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasScalar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, scalar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, scalar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serialization.Serialization.TestParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Serialization.TestParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Serialization.TestParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Serialization.TestParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Serialization.TestParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Serialization.TestParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serialization.Serialization.TestParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serialization.Serialization.TestParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serialization.Serialization.TestParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Serialization.TestParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serialization.Serialization.TestParam prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.TestParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.TestParam)
        serialization.Serialization.TestParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serialization.Serialization.internal_static_serialization_TestParam_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serialization.Serialization.internal_static_serialization_TestParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serialization.Serialization.TestParam.class, serialization.Serialization.TestParam.Builder.class);
      }

      // Construct using serialization.Serialization.TestParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        scalar_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serialization.Serialization.internal_static_serialization_TestParam_descriptor;
      }

      public serialization.Serialization.TestParam getDefaultInstanceForType() {
        return serialization.Serialization.TestParam.getDefaultInstance();
      }

      public serialization.Serialization.TestParam build() {
        serialization.Serialization.TestParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serialization.Serialization.TestParam buildPartial() {
        serialization.Serialization.TestParam result = new serialization.Serialization.TestParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.scalar_ = scalar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serialization.Serialization.TestParam) {
          return mergeFrom((serialization.Serialization.TestParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serialization.Serialization.TestParam other) {
        if (other == serialization.Serialization.TestParam.getDefaultInstance()) return this;
        if (other.hasScalar()) {
          setScalar(other.getScalar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasScalar()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serialization.Serialization.TestParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serialization.Serialization.TestParam) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double scalar_ ;
      /**
       * <code>required double scalar = 1;</code>
       */
      public boolean hasScalar() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double scalar = 1;</code>
       */
      public double getScalar() {
        return scalar_;
      }
      /**
       * <code>required double scalar = 1;</code>
       */
      public Builder setScalar(double value) {
        bitField0_ |= 0x00000001;
        scalar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double scalar = 1;</code>
       */
      public Builder clearScalar() {
        bitField0_ = (bitField0_ & ~0x00000001);
        scalar_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serialization.TestParam)
    }

    static {
      defaultInstance = new TestParam(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.TestParam)
  }

  public static final int CUSTOMIZEDDATA_FIELD_NUMBER = 1000;
  /**
   * <code>extend .serialization.CustomParam { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      serialization.Model.CustomParam,
      serialization.Serialization.TestParam> customizedData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        serialization.Serialization.TestParam.class,
        serialization.Serialization.TestParam.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_TestParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_TestParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0test/resources/serialization/serializa" +
      "tion.proto\022\rserialization\032(main/resource" +
      "s/serialization/model.proto\"\033\n\tTestParam" +
      "\022\016\n\006scalar\030\001 \002(\001:M\n\016customizedData\022\032.ser" +
      "ialization.CustomParam\030\350\007 \001(\0132\030.serializ" +
      "ation.TestParam"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          serialization.Model.getDescriptor(),
        }, assigner);
    internal_static_serialization_TestParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serialization_TestParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_TestParam_descriptor,
        new java.lang.String[] { "Scalar", });
    customizedData.internalInit(descriptor.getExtensions().get(0));
    serialization.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
