# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      - wget https://raw.githubusercontent.com/analytics-zoo/gha-cicd-env/main/python-requirements/requirements-doc.txt

sphinx:
  configuration: docs/readthedocs/source/conf.py

python:
  install:
    - requirements: ./requirements-doc.txt
