name: 'Mac Orca Python UT Spark3.1'
description: 'Mac Orca Python UT Spark3.1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source ~/.bash_profile
        source activate py37
        pip uninstall -y bigdl-dllib bigdl-orca bigdl-chronos bigdl-orca-spark3 bigdl-dllib-spark3 bigdl-chronos-spark3  pyspark
        export KERAS_BACKEND=tensorflow
        #export SPARK_HOME=/opt/work/spark-3.4.1
        export MASTER=local[4]
        export HDFS_URI=/Users/arda/data
        export PATH=/opt/maven/apache-maven-3.6.3/bin:$PATH
        
        gsed -i "s/'pyspark=='+PYSPARK_VERSION/'pyspark==3.1.3'/g" python/dllib/src/setup.py
        gsed -i "s/name='bigdl-dllib'/name='bigdl-dllib-spark3'/g" python/dllib/src/setup.py
        gsed -i "s/dist\/bigdl_dllib-/dist\/bigdl_dllib_spark3-/g" python/dllib/dev/release/release.sh
        bash python/dllib/dev/release/release.sh mac default false false -Dspark.version=3.4.1 -P spark_3.x -Ddata-store-url=http://10.239.45.10:8081/repository/raw -U

        gsed -i "s/bigdl-dllib==/bigdl-dllib-spark3==/g" python/orca/src/setup.py
        gsed -i "s/name='bigdl-orca'/name='bigdl-orca-spark3'/g" python/orca/src/setup.py
        gsed -i "s/dist\/bigdl_orca-/dist\/bigdl_orca_spark3-/g" python/orca/dev/release/release.sh
        bash python/orca/dev/release/release.sh mac default true false -Dspark.version=3.4.1 -P spark_3.x

        echo "Running py37 tests"
        # install dllib
        pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib*-py3-none-macosx_10_11_x86_64.whl	
        # install orca
        pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca*-py3-none-macosx_10_11_x86_64.whl		
        
        python/orca/dev/test/run-pytests-spark.sh
        conda deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        
