name: Download LLM binary files
description: Download built binary files from github artifact

runs:
  using: "composite"
  steps:
    - name: Download all build files
      uses: actions/download-artifact@4.1.7
    - name: Move build resources
      shell: bash
      run: |
        rm -rf python/llm/llm-binary || true
        mkdir -p python/llm/llm-binary
        mv linux-avx2/* python/llm/llm-binary/
        mv linux-avx512/* python/llm/llm-binary/
        mv linux-avxvnni/* python/llm/llm-binary/
        mv linux-avx/* python/llm/llm-binary/
        mv linux-amx/* python/llm/llm-binary/
        mv windows-avx2/* python/llm/llm-binary/
        mv windows-avx-vnni/* python/llm/llm-binary/
        mv windows-avx/* python/llm/llm-binary/
        rm -rf linux-avx2 || true
        rm -rf linux-avx512 || true
        rm -rf linux-avxvnni || true
        rm -rf linux-avx || true
        rm -rf linux-amx || true
        rm -rf windows-avx2 || true
        rm -rf windows-avx-vnni || true
        rm -rf windows-avx || true
