{{- if .Values.serviceAccounts.spark.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.sparkJobNamespace }}
{{- with .Values.serviceAccounts.spark.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
{{- end }}
