name: 'Run Orca Python ExampleTest'
description: 'Run Orca Python ExampleTest'
runs:
  using: "composite"
  steps:
    - name: Setup Env
      run: |
        apt-get update
        apt-get install wget

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -r python/orca/dev/example/requirements-ray.txt -y
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r python/orca/dev/example/requirements-ray.txt 
        pip uninstall -y opencv-python-headless
        pip install opencv-python-headless
    - name: Run Test
      run: |
        export MAVEN_OPTS="-XX:MaxPermSize=3G -Xmx100G -XX:ReservedCodeCacheSize=512m"
        export _JAVA_OPTIONS="-Xmx100G -XX:MaxPermSize=3G"
        export SPARK_LOCAL_HOSTNAME=localhost
        chmod a+x python/orca/dev/example/run-example-tests.sh
        python/orca/dev/example/run-example-tests.sh
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}