name: 'Run Friesian Python ExampleTest Tf2 Py37 Spark3'
description: 'Run Friesian Python ExampleTest Tf2 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.4.1
        cd -
       
        wget https://archive.apache.org/dist/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz -O ${{ github.workspace }}/spark-3.4.1-bin-hadoop3.tgz
        tar -xf spark-3.4.1-bin-hadoop3.tgz -C ${{ github.workspace }}/
        export SPARK_HOME=${{ github.workspace }}/spark-3.4.1-bin-hadoop3
        
        source activate py37
        source python/friesian/dev/prepare_env.sh
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.4.1 
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} grpcio==1.43.0

        cd python/friesian/dev/test
        bash run-example-tests-tf2.6.0.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
