#!/bin/sh
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2021 Intel Corporation

ORIGBASE="$(basename "$0")"
ORIGPATH="$(dirname "$0")"

REPLACED="gramine-${ORIGBASE#graphene-}"

echo "WARNING: Graphene was renamed to Gramine recently. Consider using new executable names." >&2
echo "         (For now, we replaced call to '${ORIGBASE}' with '${REPLACED}')." >&2
echo "" >&2

exec "${ORIGPATH}/${REPLACED}" "$@"
