name: 'Run Friesian Python ExampleTest Feature Tf1 Py37 Spark3'
description: 'Run Friesian Python ExampleTest Feature Tf1 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.1.3
        cd -
       
        wget https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz -O ${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7.tgz
        tar -xf spark-3.1.3-bin-hadoop2.7.tgz -C ${{ github.workspace }}/
        export SPARK_HOME=${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7
        
        source activate py37
        source python/friesian/dev/prepare_env.sh
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.1.3 
        pip install -i https://pypi.org/simple bigdl-math bigdl-tf
        cd python/friesian/dev/test
        bash run-feature-example-tests.sh 
        bash run-example-tests-tf1.15.0.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
