name: 'Run Orca Python Horovod Tf2 Py37 Spark3'
description: 'Run Orca Python Horovod Tf2 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Install dependencies
      shell: bash
      run: |
      apt-get update
        apt-get install wget
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

    - name: Setup env
      shell: bash
      run: |
        if conda info --env | grep "orca-oython-horovod-tf2-py37-spark3"; then
            source activate orca-oython-horovod-tf2-py37-spark3
        else
            conda create -n orca-oython-horovod-tf2-py37-spark3 -y python==3.7.10 setuptools==58.0.4
            conda info --env
            source activate orca-oython-horovod-tf2-py37-spark3
        fi
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -y intel-tensorflow
        pip install cmake mxnet==1.6.0
        pip uninstall -r .github/actions/python-requirements/requirements-horovod-tf2.txt -y
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r .github/actions/python-requirements/requirements-horovod-tf2.txt 
        pip install pytest
        HOROVOD_WITH_PYTORCH=1; HOROVOD_WITH_GLOO=1; pip install --no-cache-dir horovod==0.19.2
        pip uninstall -y opencv-python-headless
        pip install opencv-python-headless
        pip install --pre --upgrade bigdl-orca-spark3

      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
