apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: bigdl-ppml-training
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: {{ .Values.nfsPath }}
    server: {{ .Values.nfsServerIp }}

