name: 'Run Orca Python Py39 Spark3'
description: 'Run Orca Python Py39 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py39
        export SPARK_LOCAL_HOSTNAME=localhost
        
        # unit test test_inference_model requires "app.properties"
        bash python/dev/release_default_linux_spark3.sh default false false false -Ddata-store-url=$HTTP_URI -U
        
        pip install -i https://pypi.python.org/simple --pre --upgrade bigdl-orca-spark3

        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} torch==1.7.1
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} torchvision==0.8.2
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} torchmetrics==0.10.0
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pyarrow==4.0.1
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pandas==1.1.5
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} h5py

        chmod a+x python/orca/dev/test/run-pytests-spark.sh
        python/orca/dev/test/run-pytests-spark.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
