#!/usr/bin/env bash

#
# Copyright 2016 The BigDL Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. `dirname $0`/prepare_env.sh

cd "`dirname $0`"

export DL_CORE_NUMBER=4

if [ -n $CONDA_DEFAULT_ENV ];
then
    export PYTHON_EXECUTABLES=("python")
fi

RUN_PART1=0
RUN_PART2=0
if [ $1 = 1 ]; then
RUN_PART1=1
RUN_PART2=0
elif [ $1 = 2 ]; then
RUN_PART1=0
RUN_PART2=1
else
RUN_PART1=1
RUN_PART2=1
fi

if [ $RUN_PART1 = 1 ]; then
echo "Running dllib tests Part 1"
for p in ${PYTHON_EXECUTABLES[@]}
do
    echo "${cyan}Using python version: $p${reset}"
    export PYTHON_EXECUTABLE=$p
    export PYSPARK_PYTHON=$p
    export PYSPARK_DRIVER_PYTHON=$p
    $p -m pytest -v --junitxml result_bigdl_${p}.xml --doctest-modules ../../dllib/src/bigdl \
    --ignore=../../dllib/src/bigdl/dllib/feature/dataset/ \
    --ignore=../../dllib/src/bigdl/dllib/utils/tf_utils.py \
    --ignore=../../dllib/src/bigdl/dllib/examples/ \
    --ignore=../../dllib/src/bigdl/dllib/models/

    exit_status=$?
    if [ $exit_status -ne 0 ];
    then
        exit $exit_status
    fi
done
fi


if [ $RUN_PART2 = 1 ]; then
echo "Running dllib tests Part 2"
for p in ${PYTHON_EXECUTABLES[@]}
do
    echo "${cyan}Using python version: $p${reset}"
    export PYTHON_EXECUTABLE=$p
    export PYSPARK_PYTHON=$p
    export PYSPARK_DRIVER_PYTHON=$p
    $p -m pytest -v --junitxml result_test_${p}.xml  ../../../python/dllib/test/ \
    --ignore=../../dllib/test/bigdl/caffe/ \
    --ignore=../../dllib/test/bigdl/test_utils.py \
    --ignore=../../dllib/test/bigdl/test_zoo_util.py

    exit_status=$?
    if [ $exit_status -ne 0 ];
    then
        exit $exit_status
    fi
done
fi
