name: 'Run Friesian Python Py37 Spark3'
description: 'Run Friesian Python Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.4.1
        cd -
       
        wget https://archive.apache.org/dist/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz -O ${{ github.workspace }}/spark-3.4.1-bin-hadoop3.tgz
        tar -xf spark-3.4.1-bin-hadoop3.tgz -C ${{ github.workspace }}/
        export SPARK_HOME=${{ github.workspace }}/spark-3.4.1-bin-hadoop3

        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.4.1 
        chmod a+x python/friesian/dev/test/run-pytests-friesian
        python/friesian/dev/test/run-pytests-friesian
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
