apiVersion: v1
kind: Service
metadata:
  name: {{ include "friesian-serving.feature.fullname" . }}
  namespace: {{ template "friesian-serving.namespace" . }}
  labels:
    app: {{ template "friesian-serving.name" . }}-feature
    {{ include "friesian-serving.labels" . | nindent 4 }}
    {{- if .Values.feature.labels }}
    {{ toYaml .Values.feature.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.feature.annotations }}
  annotations:
    {{ toYaml .Values.feature.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.feature.service.type }}
  clusterIP: {{ .Values.feature.service.clusterIP }}
  selector:
    app: {{ template "friesian-serving.name" . }}-feature
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.feature.config.servicePort }}
      targetPort: {{ .Values.feature.config.servicePort }}
    - name: monitor
      port: {{ .Values.feature.config.monitorPort }}
      targetPort: {{ .Values.feature.config.monitorPort }}
      protocol: TCP