apiVersion: v1
kind: Pod
metadata:
  name: torchserve-frontend
  namespace: bigdl-ppml-serving
  labels:
    app: torchserve-frontend
spec:
  containers:
  - name: bigdl-torchserve-frontend-pod
    image: {{ .Values.imageName }}
    command: ['sh' , '-c', 'bash /ppml/torchserve/frontend-entrypoint.sh']
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp
      name: nfs-storage
    {{- if eq .Values.TEEMode "sgx" }}
    - name: device-plugin
      mountPath: /var/lib/kubelet/device-plugins
    - name: aesm-socket
      mountPath: /var/run/aesmd/aesm.socket
    {{- end }}
    env:
    - name: SGX_ENABLED
    {{- if eq .Values.TEEMode "sgx" }}
      value: "true"
    {{- else }}
      value: "false"
    {{- end }} 
    - name: PCCS_URL
      value: "{{ .Values.PCCSUrl }}"
    - name: ATTESTATION
    {{- if eq .Values.TEEMode "native" }}
      value: "false"
    {{- else }}
      value: "true"
    {{- end }}
    - name: INFERENCE_PORT
      value: "{{ .Values.inferencePort }}"
    - name: MANAGEMENT_PORT
      value: "{{ .Values.managementPort }}"
    - name: METRICS_PORT
      value: "{{ .Values.metricsPort }}"
    - name: BACKEND_NUM
      value: "{{ .Values.backendNum }}"
    - name: MODEL_NAME
      value: "{{ .Values.modelName }}"
    - name: MODEL_DECRYPTION
      value: "{{ .Vaules.modelDecryption }}"
    - name: DECRYPTION_KEY
      value: "{{ .Values.decryptionKey }}"
    resources:
      requests:
        cpu: 2
        memory: 10Gi
      {{- if eq .Values.TEEMode "sgx" }}
        sgx.intel.com/epc: 21474836280
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
      limits:
        cpu: 2
        memory: 10Gi
        sgx.intel.com/epc: 21474836280
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
      {{- end }} 
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
  {{- if eq .Values.TEEMode "sgx" }}
  - name: device-plugin
    hostPath:
      path: /var/lib/kubelet/device-plugins
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
  {{- end }}
