#!/usr/bin/env bash

#
# Copyright 2016 The BigDL Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export FTP_URI=$FTP_URI
. `dirname $0`/../prepare_env.sh

cd "`dirname $0`"

# download model from ftp
if [ -f ./distilbert-base-uncased ]
then
    echo "model distilbert-base-uncased already exists"
else
    wget $FTP_URI/analytics-zoo-models/distilbert-base-uncased.zip
    unzip distilbert-base-uncased.zip
fi

echo "Running Friesian feature tests"
python -m pytest -v ../../test/bigdl/friesian/feature/
exit_status=$?
if [ $exit_status -ne 0 ];
then
    exit $exit_status
fi

# remove the model
rm -rf ./distilbert-base-uncased
rm -f ./distilbert-base-uncased.zip
