#!/usr/bin/env bash

#
# Licensed to Intel Corporation under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Intel Corporation licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


DL_PYTHON_HOME="$(cd "`dirname $0`"/..; pwd)"

DL_HOME="$(cd "`dirname $0`"/../../../../../; pwd)"

echo "DL_HOME: $DL_HOME"
echo "SPARK_HOME": $SPARK_HOME

if [ -z ${SPARK_HOME+x} ]; then echo "SPARK_HOME is unset"; exit 1; else echo "SPARK_HOME is set to '$SPARK_HOME'"; fi

export PYTHONPATH=$SPARK_HOME/python:$DL_PYTHON_HOME;

export SPARK_CLASSPATH=$DL_HOME/dl/target/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar

cd "`dirname $0`"
exec python -u ./run-tests.py "$@"