#!/usr/bin/bash

export MASTER=YOUR_MASTER_IP
export WORKERS=(YOUR_WORKER_IP_1 YOUR_WORKER_IP_2 YOUR_WORKER_IP_3)

export TRUSTED_CLUSTER_SERVING_DOCKER=intelanalytics/bigdl-ppml-trusted-realtime-ml-scala-graphene:2.1.0

export SOURCE_ENCLAVE_KEY_PATH=YOUR_LOCAL_ENCLAVE_KEY_PATH
export SOURCE_KEYS_PATH=YOUR_LOCAL_KEYS_PATH
export SOURCE_SECURE_PASSWORD_PATH=YOUR_LOCAL_SECURE_PASSWORD_PATH

export BIGDL_PPML_PATH=/opt/bigdl-ppml
export ENCLAVE_KEY_PATH=$BIGDL_PPML_PATH/enclave-key.pem
export KEYS_PATH=$BIGDL_PPML_PATH/keys
export SECURE_PASSWORD_PATH=$BIGDL_PPML_PATH/password
