#!/usr/bin/bash

export MASTER=YOUR_MASTER_IP
export WORKERS=(YOUR_WORKER_IP_1 YOUR_WORKER_IP_2 YOUR_WORKER_IP_3)

export TRUSTED_BIGDATA_ML_DOCKER=10.239.45.10/arda/intelanalytics/analytics-zoo-ppml-trusted-big-data-ml-python-graphene:0.11-SNAPSHOT

export SOURCE_ENCLAVE_KEY_PATH=YOUR_LOCAL_ENCLAVE_KEY_PATH
export SOURCE_KEYS_PATH=YOUR_LOCAL_KEYS_PATH
export SOURCE_SECURE_PASSWORD_PATH=YOUR_LOCAL_SECURE_PASSWORD_PATH
export SOURCE_DATA_PATH=YOUR_LOCAL_DATA_PATH

export AZ_PPML_PATH=/opt/analytics-zoo-ppml
export ENCLAVE_KEY_PATH=$AZ_PPML_PATH/enclave-key.pem
export KEYS_PATH=$AZ_PPML_PATH/keys
export SECURE_PASSWORD_PATH=$AZ_PPML_PATH/password
export DATA_PATH=$AZ_PPML_PATH/data