name: 'PPML-spark-Local-Example-Tests-on-Gramine'
description: 'PPML-spark-Local-Example-Tests-on-Gramine'
inputs:
  image:
    description: 'image'
    required: true
    default: '10.239.45.10/arda/intelanalytics/bigdl-ppml-trusted-bigdata-gramine-reference'
  image-tag:
    description: 'image tag'
    required: true
    default: 'latest'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set Variable
      shell: bash
      env:
        DEFAULT_IMAGE: ${{ inputs.image }}:${{ inputs.image-tag }}
      run: |
        echo "HDFS_ADDRESS=172.168.0.206:9000" >> $GITHUB_ENV
        echo "CONTAINER_NAME=spark-examples-test-gramine" >> $GITHUB_ENV
        echo "IMAGE=${{ env.DEFAULT_IMAGE }}" >> $GITHUB_ENV

    - name: Start Container
      shell: bash
      run: |
        set -x
        docker pull ${IMAGE}
        docker rm -f ${CONTAINER_NAME}
        docker run -id --privileged --net=host --name ${CONTAINER_NAME} \
        --cpus=10 \
        --oom-kill-disable \
        --device=/dev/sgx/enclave \
        --device=/dev/sgx/provision \
        -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
        -v $KEYS_PATH:/ppml/keys \
        -v $SECURE_PASSWORD_PATH:/ppml/password \
        -v $KUBECONFIG_PATH:/root/.kube/config \
        -v $NFS_INPUT_PATH:/ppml/data \
        -e RUNTIME_SPARK_MASTER=k8s://https://$LOCAL_IP:6443 \
        -e RUNTIME_K8S_SERVICE_ACCOUNT=spark \
        -e LOCAL_IP=$LOCAL_IP \
        -e RUNTIME_K8S_SPARK_IMAGE=$IMAGE \
        -e RUNTIME_DRIVER_HOST=$LOCAL_IP \
        -e RUNTIME_DRIVER_PORT=54321 \
        -e RUNTIME_DRIVER_MEMORY=1g \
        $IMAGE bash
    - name: Spark Examples Test
      shell: bash
      run: |
        docker exec -i $CONTAINER_NAME bash -c "/ppml/init.sh"

        echo "##### Test on /ppml/scripts/start-pyspark-sqlApi-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-pyspark-sqlApi-on-local-sgx.sh"
        /opt/hadoop-3.2.0/bin/hadoop fs -rm -r -f hdfs://$HDFS_ADDRESS/spark-warehous

        echo "##### Test on /ppml/scripts/start-pyspark-sqlexamples-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-pyspark-sqlexamples-on-local-sgx.sh"

        echo "##### Test on /ppml/scripts/start-pyspark-pi-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-pyspark-pi-on-local-sgx.sh"

        echo "##### Test on /ppml/scripts/start-pyspark-simpleexamples-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-pyspark-simpleexamples-on-local-sgx.sh"
        /opt/hadoop-3.2.0/bin/hadoop fs -rm -r -f hdfs://$HDFS_ADDRESS/spark-warehous

        echo "##### Test on /ppml/scripts/start-spark-sqlexamples-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-spark-sqlexamples-on-local-sgx.sh"

        echo "##### Test on /ppml/scripts/start-python-helloword-on-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-python-helloword-on-sgx.sh"

        echo "##### Test on /ppml/scripts/start-python-numpy-on-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-python-numpy-on-sgx.sh"

        echo "##### Test on /ppml/scripts/start-spark-pi-on-local-sgx.sh"
        docker exec -i $CONTAINER_NAME bash -c "/ppml/scripts/start-spark-pi-on-local-sgx.sh"
