// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorboard/src/event.proto

package org.tensorflow.util;

public final class EventProtos {
  private EventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorboard_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorboard_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorboard_LogMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorboard_LogMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorboard_SessionLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorboard_SessionLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorboard_TaggedRunMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorboard_TaggedRunMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033tensorboard/src/event.proto\022\013tensorboa" +
      "rd\032\035tensorboard/src/summary.proto\"\277\002\n\005Ev" +
      "ent\022\021\n\twall_time\030\001 \001(\001\022\014\n\004step\030\002 \001(\003\022\026\n\014" +
      "file_version\030\003 \001(\tH\000\022\023\n\tgraph_def\030\004 \001(\014H" +
      "\000\022\'\n\007summary\030\005 \001(\0132\024.tensorboard.Summary" +
      "H\000\022.\n\013log_message\030\006 \001(\0132\027.tensorboard.Lo" +
      "gMessageH\000\022.\n\013session_log\030\007 \001(\0132\027.tensor" +
      "board.SessionLogH\000\022=\n\023tagged_run_metadat" +
      "a\030\010 \001(\0132\036.tensorboard.TaggedRunMetadataH" +
      "\000\022\030\n\016meta_graph_def\030\t \001(\014H\000B\006\n\004what\"\226\001\n\n",
      "LogMessage\022,\n\005level\030\001 \001(\0162\035.tensorboard." +
      "LogMessage.Level\022\017\n\007message\030\002 \001(\t\"I\n\005Lev" +
      "el\022\013\n\007UNKNOWN\020\000\022\t\n\005DEBUG\020\n\022\010\n\004INFO\020\024\022\010\n\004" +
      "WARN\020\036\022\t\n\005ERROR\020(\022\t\n\005FATAL\0202\"\267\001\n\nSession" +
      "Log\0225\n\006status\030\001 \001(\0162%.tensorboard.Sessio" +
      "nLog.SessionStatus\022\027\n\017checkpoint_path\030\002 " +
      "\001(\t\022\013\n\003msg\030\003 \001(\t\"L\n\rSessionStatus\022\026\n\022STA" +
      "TUS_UNSPECIFIED\020\000\022\t\n\005START\020\001\022\010\n\004STOP\020\002\022\016" +
      "\n\nCHECKPOINT\020\003\"6\n\021TaggedRunMetadata\022\013\n\003t" +
      "ag\030\001 \001(\t\022\024\n\014run_metadata\030\002 \001(\014B\'\n\023org.te",
      "nsorflow.utilB\013EventProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.SummaryProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorboard_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorboard_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorboard_Event_descriptor,
        new java.lang.String[] { "WallTime", "Step", "FileVersion", "GraphDef", "Summary", "LogMessage", "SessionLog", "TaggedRunMetadata", "MetaGraphDef", "What", });
    internal_static_tensorboard_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorboard_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorboard_LogMessage_descriptor,
        new java.lang.String[] { "Level", "Message", });
    internal_static_tensorboard_SessionLog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorboard_SessionLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorboard_SessionLog_descriptor,
        new java.lang.String[] { "Status", "CheckpointPath", "Msg", });
    internal_static_tensorboard_TaggedRunMetadata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorboard_TaggedRunMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorboard_TaggedRunMetadata_descriptor,
        new java.lang.String[] { "Tag", "RunMetadata", });
    org.tensorflow.framework.SummaryProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
