// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorboard/src/event.proto

package org.tensorflow.util;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorboard.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Timestamp of the event.
   * </pre>
   *
   * <code>optional double wall_time = 1;</code>
   */
  double getWallTime();

  /**
   * <pre>
   * Global step of the event.
   * </pre>
   *
   * <code>optional int64 step = 2;</code>
   */
  long getStep();

  /**
   * <pre>
   * An event file was started, with the specified version.
   * This is use to identify the contents of the record IO files
   * easily.  Current version is "brain.Event:2".  All versions
   * start with "brain.Event:".
   * </pre>
   *
   * <code>optional string file_version = 3;</code>
   */
  java.lang.String getFileVersion();
  /**
   * <pre>
   * An event file was started, with the specified version.
   * This is use to identify the contents of the record IO files
   * easily.  Current version is "brain.Event:2".  All versions
   * start with "brain.Event:".
   * </pre>
   *
   * <code>optional string file_version = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileVersionBytes();

  /**
   * <pre>
   * An encoded version of a GraphDef.
   * </pre>
   *
   * <code>optional bytes graph_def = 4;</code>
   */
  com.google.protobuf.ByteString getGraphDef();

  /**
   * <pre>
   * A summary was generated.
   * </pre>
   *
   * <code>optional .tensorboard.Summary summary = 5;</code>
   */
  org.tensorflow.framework.Summary getSummary();
  /**
   * <pre>
   * A summary was generated.
   * </pre>
   *
   * <code>optional .tensorboard.Summary summary = 5;</code>
   */
  org.tensorflow.framework.SummaryOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   * The user output a log message. Not all messages are logged, only ones
   * generated via the Python tensorboard_logging module.
   * </pre>
   *
   * <code>optional .tensorboard.LogMessage log_message = 6;</code>
   */
  org.tensorflow.util.LogMessage getLogMessage();
  /**
   * <pre>
   * The user output a log message. Not all messages are logged, only ones
   * generated via the Python tensorboard_logging module.
   * </pre>
   *
   * <code>optional .tensorboard.LogMessage log_message = 6;</code>
   */
  org.tensorflow.util.LogMessageOrBuilder getLogMessageOrBuilder();

  /**
   * <pre>
   * The state of the session which can be used for restarting after crashes.
   * </pre>
   *
   * <code>optional .tensorboard.SessionLog session_log = 7;</code>
   */
  org.tensorflow.util.SessionLog getSessionLog();
  /**
   * <pre>
   * The state of the session which can be used for restarting after crashes.
   * </pre>
   *
   * <code>optional .tensorboard.SessionLog session_log = 7;</code>
   */
  org.tensorflow.util.SessionLogOrBuilder getSessionLogOrBuilder();

  /**
   * <pre>
   * The metadata returned by running a session.run() call.
   * </pre>
   *
   * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
   */
  org.tensorflow.util.TaggedRunMetadata getTaggedRunMetadata();
  /**
   * <pre>
   * The metadata returned by running a session.run() call.
   * </pre>
   *
   * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
   */
  org.tensorflow.util.TaggedRunMetadataOrBuilder getTaggedRunMetadataOrBuilder();

  /**
   * <pre>
   * An encoded version of a MetaGraphDef.
   * </pre>
   *
   * <code>optional bytes meta_graph_def = 9;</code>
   */
  com.google.protobuf.ByteString getMetaGraphDef();

  public org.tensorflow.util.Event.WhatCase getWhatCase();
}
