name: 'Run Orca Python ExampleTest'
description: 'Run Orca Python ExampleTest'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export MAVEN_OPTS="-XX:MaxPermSize=3G -Xmx100G -XX:ReservedCodeCacheSize=512m"
        export _JAVA_OPTIONS="-Xmx100G -XX:MaxPermSize=3G"
        export SPARK_LOCAL_HOSTNAME=localhost
        chmod a+x python/orca/dev/example/run-example-tests.sh
        python/orca/dev/example/run-example-tests.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}