grep -rl com.intel.analytics.bigdl.utils --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.utils/com.intel.analytics.bigdl.dllib.utils/g'
grep -rl com.intel.analytics.bigdl.optim --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.optim/com.intel.analytics.bigdl.dllib.optim/g'
grep -rl com.intel.analytics.bigdl.tensor --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.tensor/com.intel.analytics.bigdl.dllib.tensor/g'
grep -rl com.intel.analytics.bigdl.nn --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.nn/com.intel.analytics.bigdl.dllib.nn/g'
grep -rl com.intel.analytics.bigdl.models --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.models/com.intel.analytics.bigdl.dllib.models/g'
grep -rl com.intel.analytics.bigdl.dataset --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.dataset/com.intel.analytics.bigdl.dllib.feature.dataset/g'
grep -rl com.intel.analytics.bigdl.transform --include \*.scala . | xargs sed -i 's/com.intel.analytics.bigdl.transform/com.intel.analytics.bigdl.dllib.feature.transform/g'
grep -rl com.intel.analytics.zoo.feature --include \*.scala . | xargs sed -i 's/com.intel.analytics.zoo.feature/com.intel.analytics.bigdl.dllib.feature/g'
grep -rl com.intel.analytics.zoo.pipeline.api.keras --include \*.scala . | xargs sed -i 's/com.intel.analytics.zoo.pipeline.api.keras/com.intel.analytics.bigdl.dllib.keras/g'
grep -rl com.intel.analytics.zoo.common.NNContext --include \*.scala . | xargs sed -i 's/com.intel.analytics.zoo.common.NNContext/com.intel.analytics.bigdl.dllib.NNContext/g'
grep -rl com.intel.analytics.zoo.common --include \*.scala . | xargs sed -i 's/com.intel.analytics.zoo.common/com.intel.analytics.bigdl.dllib.common/g'
grep -rl com.intel.analytics.zoo.pipeline.nnframes --include \*.scala . | xargs sed -i 's/com.intel.analytics.zoo.pipeline.nnframes/com.intel.analytics.bigdl.dllib.nnframes/g'
                                               
grep -rl bigdl.dataset --include \*.py . | xargs sed -i 's/bigdl.dataset/bigdl.dllib.feature.dataset/g'
grep -rl bigdl.transform --include \*.py . | xargs sed -i 's/bigdl.transform/bigdl.dllib.feature.transform/g'
grep -rl bigdl.nn --include \*.py . | xargs sed -i 's/bigdl.nn/bigdl.dllib.nn/g'
grep -rl bigdl.optim --include \*.py . | xargs sed -i 's/bigdl.optim/bigdl.dllib.optim/g'
grep -rl bigdl.util --include \*.py . | xargs sed -i 's/bigdl.util/bigdl.dllib.utils/g'
grep -rl zoo.common --include \*.py . | xargs sed -i 's/zoo.common/bigdl.dllib.utils/g'
grep -rl bigdl.dllib.utils.nncontext --include \*.py . | xargs sed -i 's/bigdl.dllib.utils.nncontext/bigdl.dllib.nncontext/g'
grep -rl zoo.feature . | xargs sed -i 's/zoo.feature/bigdl.dllib.feature/g'
grep -rl zoo.pipeline.nnframes . | xargs sed -i 's/zoo.pipeline.nnframes/bigdl.dllib.nnframes/g'
grep -rl zoo.pipeline.api.keras . | xargs sed -i 's/zoo.pipeline.api.keras/bigdl.dllib.keras/g'
grep -rl zoo.pipeline.api.autograd . | xargs sed -i 's/zoo.pipeline.api.autograd/bigdl.dllib.keras.autograd/g'
