#!/bin/bash

set -e

#detect paths
export BIGDL_ENV=`python -c """from bigdl.dllib.utils.engine import *
print(' ' + get_bigdl_conf(), end=' ')
bigdl_jars = get_bigdl_jars()
print(','.join(bigdl_jars), end=' ')
print(':'.join(bigdl_jars), end=' ')
"""
`

#setup env
IFS=$' ' array=($(echo $BIGDL_ENV))
len=${#array[@]}
export BIGDL_CONF="${array[$len-3]}"
export BIGDL_JAR="${array[$len-2]}"
export BIGDL_CLASSPATH="${array[$len-1]}"

# Check env
if [ -z ${BIGDL_CONF} ]; then
    echo "Cannot find BIGDL_CONF in BIGDL_ENV ${BIGDL_ENV}"
    exit 1
fi

if [ -z $BIGDL_JAR ]; then
    echo "Cannot find BIGDL_JAR in BIGDL_ENV ${BIGDL_ENV}"
    exit 1
fi

if [ -z $BIGDL_JAR ]; then
    echo "Cannot find BIGDL_CLASSPATH in BIGDL_ENV ${BIGDL_ENV}"
    exit 1
fi

spark-submit \
  --properties-file ${BIGDL_CONF} \
  --jars ${BIGDL_JAR} \
  --conf spark.driver.extraClassPath=${BIGDL_CLASSPATH} \
  --conf spark.executor.extraClassPath=${BIGDL_CLASSPATH} \
  $*
