cp -f /usr/lib/x86_64-linux-gnu/*sgx* .              --remove-destination
cp -f /usr/lib/x86_64-linux-gnu/*dcap* .             --remove-destination
# use mount way
#cp /etc/sgx_default_qcnl.conf /opt/occlum_spark/image/etc/

cp -f     /lib/x86_64-linux-gnu/libsgx_default_qcnl_wrapper.so.1                      .       --remove-destination
cp -f      /lib/x86_64-linux-gnu/libcurl.so.4                                         .       --remove-destination
cp -f  /lib/x86_64-linux-gnu/libm.so.6                                                .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libnghttp2.so.14                                       .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libidn2.so.0                                           .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/librtmp.so.1                                           .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libssh.so.4                                  .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libpsl.so.5                                        .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libssl.so.1.1                                          .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libcrypto.so.1.1                                       .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libgssapi_krb5.so.2                          .       --remove-destination
cp -f            /lib/x86_64-linux-gnu/libldap_r-2.4.so.2                             .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/liblber-2.4.so.2                             .       --remove-destination
cp -f                  /lib/x86_64-linux-gnu/libbrotlidec.so.1                        .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libz.so.1                                          .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libunistring.so.2                            .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libgnutls.so.30                              .       --remove-destination
cp -f            /lib/x86_64-linux-gnu/libhogweed.so.5                                .       --remove-destination
cp -f          /lib/x86_64-linux-gnu/libnettle.so.7                                   .       --remove-destination
cp -f       /lib/x86_64-linux-gnu/libgmp.so.10                                        .       --remove-destination
cp -f      /lib/x86_64-linux-gnu/libdl.so.2                                           .       --remove-destination
cp -f  /lib/x86_64-linux-gnu/libkrb5.so.3                                             .       --remove-destination
cp -f          /lib/x86_64-linux-gnu/libk5crypto.so.3                                 .       --remove-destination
cp -f      /lib/x86_64-linux-gnu/libcom_err.so.2                                      .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libkrb5support.so.0                                .       --remove-destination
cp -f     /lib/x86_64-linux-gnu/libresolv.so.2                                        .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libsasl2.so.2                                      .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libgssapi.so.3                                     .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libbrotlicommon.so.1                         .       --remove-destination
cp -f          /lib/x86_64-linux-gnu/libp11-kit.so.0                                  .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libtasn1.so.6                                      .       --remove-destination
cp -f            /lib/x86_64-linux-gnu/libkeyutils.so.1                               .       --remove-destination
cp -f  /lib/x86_64-linux-gnu/libheimntlm.so.0                                         .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libkrb5.so.26                                          .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libasn1.so.8                                       .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libhcrypto.so.4                                    .       --remove-destination
cp -f            /lib/x86_64-linux-gnu/libroken.so.18                                 .       --remove-destination
cp -f          /lib/x86_64-linux-gnu/libffi.so.7                                      .       --remove-destination
cp -f              /lib/x86_64-linux-gnu/libwind.so.0                                 .       --remove-destination
cp -f      /lib/x86_64-linux-gnu/libheimbase.so.1                                     .       --remove-destination
cp -f    /lib/x86_64-linux-gnu/libhx509.so.5                                          .       --remove-destination
cp -f        /lib/x86_64-linux-gnu/libsqlite3.so.0                                    .       --remove-destination
cp -f      /lib/x86_64-linux-gnu/libcrypt.so.1                                         .      --remove-destination