name: 'Run Orca Basic Tf2 Py38 Spark3'
description: 'Run Orca Basic Tf2 Py38 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py38
        export SPARK_LOCAL_HOSTNAME=localhost
        
        bash python/dev/release_default_linux_spark3.sh default false false false -Ddata-store-url=$HTTP_URI -U
        
        # install dllib
        pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl
        # install orca
        pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl
     
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} tensorflow==2.9.0
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} grpcio==1.43.0
        pip list
        chmod a+x python/orca/dev/test/run-pytests-basic-tf2.sh
        python/orca/dev/test/run-pytests-basic-tf2.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}