((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 100)))
 (c-mode . ((c-file-style . "k&r")
            (c-basic-offset . 4)))
 (makefile-mode . ((indent-tabs-mode . t)))
 (shell-script-mode . ((indent-tabs-mode . t)))
 ("\.git/COMMIT_EDITMSG" . ((nil . ((fill-column . 80)))))
 (markdown-mode . ((fill-column . 80)))
 (rst-mode . ((fill-column . 80)))
 ((nil . ((truncate-lines . t)))
          (text-mode . ((eval . ((turn-on-auto-fill)))))))
