// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorboard/src/event.proto

package org.tensorflow.util;

import org.tensorflow.framework.Summary;
import org.tensorflow.framework.SummaryOrBuilder;

/**
 * <pre>
 * Protocol buffer representing an event that happened during
 * the execution of a Brain model.
 * </pre>
 *
 * Protobuf type {@code tensorboard.Event}
 */
public  final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorboard.Event)
    EventOrBuilder {
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    wallTime_ = 0D;
    step_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            wallTime_ = input.readDouble();
            break;
          }
          case 16: {

            step_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            whatCase_ = 3;
            what_ = s;
            break;
          }
          case 34: {
            whatCase_ = 4;
            what_ = input.readBytes();
            break;
          }
          case 42: {
            Summary.Builder subBuilder = null;
            if (whatCase_ == 5) {
              subBuilder = ((Summary) what_).toBuilder();
            }
            what_ =
                input.readMessage(Summary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Summary) what_);
              what_ = subBuilder.buildPartial();
            }
            whatCase_ = 5;
            break;
          }
          case 50: {
            LogMessage.Builder subBuilder = null;
            if (whatCase_ == 6) {
              subBuilder = ((LogMessage) what_).toBuilder();
            }
            what_ =
                input.readMessage(LogMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((LogMessage) what_);
              what_ = subBuilder.buildPartial();
            }
            whatCase_ = 6;
            break;
          }
          case 58: {
            SessionLog.Builder subBuilder = null;
            if (whatCase_ == 7) {
              subBuilder = ((SessionLog) what_).toBuilder();
            }
            what_ =
                input.readMessage(SessionLog.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((SessionLog) what_);
              what_ = subBuilder.buildPartial();
            }
            whatCase_ = 7;
            break;
          }
          case 66: {
            TaggedRunMetadata.Builder subBuilder = null;
            if (whatCase_ == 8) {
              subBuilder = ((TaggedRunMetadata) what_).toBuilder();
            }
            what_ =
                input.readMessage(TaggedRunMetadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((TaggedRunMetadata) what_);
              what_ = subBuilder.buildPartial();
            }
            whatCase_ = 8;
            break;
          }
          case 74: {
            whatCase_ = 9;
            what_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EventProtos.internal_static_tensorboard_Event_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EventProtos.internal_static_tensorboard_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Event.class, Event.Builder.class);
  }

  private int whatCase_ = 0;
  private java.lang.Object what_;
  public enum WhatCase
      implements com.google.protobuf.Internal.EnumLite {
    FILE_VERSION(3),
    GRAPH_DEF(4),
    SUMMARY(5),
    LOG_MESSAGE(6),
    SESSION_LOG(7),
    TAGGED_RUN_METADATA(8),
    META_GRAPH_DEF(9),
    WHAT_NOT_SET(0);
    private final int value;
    private WhatCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WhatCase valueOf(int value) {
      return forNumber(value);
    }

    public static WhatCase forNumber(int value) {
      switch (value) {
        case 3: return FILE_VERSION;
        case 4: return GRAPH_DEF;
        case 5: return SUMMARY;
        case 6: return LOG_MESSAGE;
        case 7: return SESSION_LOG;
        case 8: return TAGGED_RUN_METADATA;
        case 9: return META_GRAPH_DEF;
        case 0: return WHAT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public WhatCase
  getWhatCase() {
    return WhatCase.forNumber(
        whatCase_);
  }

  public static final int WALL_TIME_FIELD_NUMBER = 1;
  private double wallTime_;
  /**
   * <pre>
   * Timestamp of the event.
   * </pre>
   *
   * <code>optional double wall_time = 1;</code>
   */
  public double getWallTime() {
    return wallTime_;
  }

  public static final int STEP_FIELD_NUMBER = 2;
  private long step_;
  /**
   * <pre>
   * Global step of the event.
   * </pre>
   *
   * <code>optional int64 step = 2;</code>
   */
  public long getStep() {
    return step_;
  }

  public static final int FILE_VERSION_FIELD_NUMBER = 3;
  /**
   * <pre>
   * An event file was started, with the specified version.
   * This is use to identify the contents of the record IO files
   * easily.  Current version is "brain.Event:2".  All versions
   * start with "brain.Event:".
   * </pre>
   *
   * <code>optional string file_version = 3;</code>
   */
  public java.lang.String getFileVersion() {
    java.lang.Object ref = "";
    if (whatCase_ == 3) {
      ref = what_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (whatCase_ == 3) {
        what_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * An event file was started, with the specified version.
   * This is use to identify the contents of the record IO files
   * easily.  Current version is "brain.Event:2".  All versions
   * start with "brain.Event:".
   * </pre>
   *
   * <code>optional string file_version = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFileVersionBytes() {
    java.lang.Object ref = "";
    if (whatCase_ == 3) {
      ref = what_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (whatCase_ == 3) {
        what_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRAPH_DEF_FIELD_NUMBER = 4;
  /**
   * <pre>
   * An encoded version of a GraphDef.
   * </pre>
   *
   * <code>optional bytes graph_def = 4;</code>
   */
  public com.google.protobuf.ByteString getGraphDef() {
    if (whatCase_ == 4) {
      return (com.google.protobuf.ByteString) what_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int SUMMARY_FIELD_NUMBER = 5;
  /**
   * <pre>
   * A summary was generated.
   * </pre>
   *
   * <code>optional .tensorboard.Summary summary = 5;</code>
   */
  public Summary getSummary() {
    if (whatCase_ == 5) {
       return (Summary) what_;
    }
    return Summary.getDefaultInstance();
  }
  /**
   * <pre>
   * A summary was generated.
   * </pre>
   *
   * <code>optional .tensorboard.Summary summary = 5;</code>
   */
  public SummaryOrBuilder getSummaryOrBuilder() {
    if (whatCase_ == 5) {
       return (Summary) what_;
    }
    return Summary.getDefaultInstance();
  }

  public static final int LOG_MESSAGE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * The user output a log message. Not all messages are logged, only ones
   * generated via the Python tensorboard_logging module.
   * </pre>
   *
   * <code>optional .tensorboard.LogMessage log_message = 6;</code>
   */
  public LogMessage getLogMessage() {
    if (whatCase_ == 6) {
       return (LogMessage) what_;
    }
    return LogMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * The user output a log message. Not all messages are logged, only ones
   * generated via the Python tensorboard_logging module.
   * </pre>
   *
   * <code>optional .tensorboard.LogMessage log_message = 6;</code>
   */
  public LogMessageOrBuilder getLogMessageOrBuilder() {
    if (whatCase_ == 6) {
       return (LogMessage) what_;
    }
    return LogMessage.getDefaultInstance();
  }

  public static final int SESSION_LOG_FIELD_NUMBER = 7;
  /**
   * <pre>
   * The state of the session which can be used for restarting after crashes.
   * </pre>
   *
   * <code>optional .tensorboard.SessionLog session_log = 7;</code>
   */
  public SessionLog getSessionLog() {
    if (whatCase_ == 7) {
       return (SessionLog) what_;
    }
    return SessionLog.getDefaultInstance();
  }
  /**
   * <pre>
   * The state of the session which can be used for restarting after crashes.
   * </pre>
   *
   * <code>optional .tensorboard.SessionLog session_log = 7;</code>
   */
  public SessionLogOrBuilder getSessionLogOrBuilder() {
    if (whatCase_ == 7) {
       return (SessionLog) what_;
    }
    return SessionLog.getDefaultInstance();
  }

  public static final int TAGGED_RUN_METADATA_FIELD_NUMBER = 8;
  /**
   * <pre>
   * The metadata returned by running a session.run() call.
   * </pre>
   *
   * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
   */
  public TaggedRunMetadata getTaggedRunMetadata() {
    if (whatCase_ == 8) {
       return (TaggedRunMetadata) what_;
    }
    return TaggedRunMetadata.getDefaultInstance();
  }
  /**
   * <pre>
   * The metadata returned by running a session.run() call.
   * </pre>
   *
   * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
   */
  public TaggedRunMetadataOrBuilder getTaggedRunMetadataOrBuilder() {
    if (whatCase_ == 8) {
       return (TaggedRunMetadata) what_;
    }
    return TaggedRunMetadata.getDefaultInstance();
  }

  public static final int META_GRAPH_DEF_FIELD_NUMBER = 9;
  /**
   * <pre>
   * An encoded version of a MetaGraphDef.
   * </pre>
   *
   * <code>optional bytes meta_graph_def = 9;</code>
   */
  public com.google.protobuf.ByteString getMetaGraphDef() {
    if (whatCase_ == 9) {
      return (com.google.protobuf.ByteString) what_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (wallTime_ != 0D) {
      output.writeDouble(1, wallTime_);
    }
    if (step_ != 0L) {
      output.writeInt64(2, step_);
    }
    if (whatCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, what_);
    }
    if (whatCase_ == 4) {
      output.writeBytes(
          4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) what_));
    }
    if (whatCase_ == 5) {
      output.writeMessage(5, (Summary) what_);
    }
    if (whatCase_ == 6) {
      output.writeMessage(6, (LogMessage) what_);
    }
    if (whatCase_ == 7) {
      output.writeMessage(7, (SessionLog) what_);
    }
    if (whatCase_ == 8) {
      output.writeMessage(8, (TaggedRunMetadata) what_);
    }
    if (whatCase_ == 9) {
      output.writeBytes(
          9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) what_));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (wallTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, wallTime_);
    }
    if (step_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, step_);
    }
    if (whatCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, what_);
    }
    if (whatCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) what_));
    }
    if (whatCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (Summary) what_);
    }
    if (whatCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (LogMessage) what_);
    }
    if (whatCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (SessionLog) what_);
    }
    if (whatCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (TaggedRunMetadata) what_);
    }
    if (whatCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            9, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) what_));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Event)) {
      return super.equals(obj);
    }
    Event other = (Event) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getWallTime())
        == java.lang.Double.doubleToLongBits(
            other.getWallTime()));
    result = result && (getStep()
        == other.getStep());
    result = result && getWhatCase().equals(
        other.getWhatCase());
    if (!result) return false;
    switch (whatCase_) {
      case 3:
        result = result && getFileVersion()
            .equals(other.getFileVersion());
        break;
      case 4:
        result = result && getGraphDef()
            .equals(other.getGraphDef());
        break;
      case 5:
        result = result && getSummary()
            .equals(other.getSummary());
        break;
      case 6:
        result = result && getLogMessage()
            .equals(other.getLogMessage());
        break;
      case 7:
        result = result && getSessionLog()
            .equals(other.getSessionLog());
        break;
      case 8:
        result = result && getTaggedRunMetadata()
            .equals(other.getTaggedRunMetadata());
        break;
      case 9:
        result = result && getMetaGraphDef()
            .equals(other.getMetaGraphDef());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + WALL_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWallTime()));
    hash = (37 * hash) + STEP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStep());
    switch (whatCase_) {
      case 3:
        hash = (37 * hash) + FILE_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getFileVersion().hashCode();
        break;
      case 4:
        hash = (37 * hash) + GRAPH_DEF_FIELD_NUMBER;
        hash = (53 * hash) + getGraphDef().hashCode();
        break;
      case 5:
        hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
        hash = (53 * hash) + getSummary().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LOG_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLogMessage().hashCode();
        break;
      case 7:
        hash = (37 * hash) + SESSION_LOG_FIELD_NUMBER;
        hash = (53 * hash) + getSessionLog().hashCode();
        break;
      case 8:
        hash = (37 * hash) + TAGGED_RUN_METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getTaggedRunMetadata().hashCode();
        break;
      case 9:
        hash = (37 * hash) + META_GRAPH_DEF_FIELD_NUMBER;
        hash = (53 * hash) + getMetaGraphDef().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Protocol buffer representing an event that happened during
   * the execution of a Brain model.
   * </pre>
   *
   * Protobuf type {@code tensorboard.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorboard.Event)
    EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventProtos.internal_static_tensorboard_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventProtos.internal_static_tensorboard_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Event.class, Event.Builder.class);
    }

    // Construct using Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      wallTime_ = 0D;

      step_ = 0L;

      whatCase_ = 0;
      what_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EventProtos.internal_static_tensorboard_Event_descriptor;
    }

    public Event getDefaultInstanceForType() {
      return Event.getDefaultInstance();
    }

    public Event build() {
      Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Event buildPartial() {
      Event result = new Event(this);
      result.wallTime_ = wallTime_;
      result.step_ = step_;
      if (whatCase_ == 3) {
        result.what_ = what_;
      }
      if (whatCase_ == 4) {
        result.what_ = what_;
      }
      if (whatCase_ == 5) {
        if (summaryBuilder_ == null) {
          result.what_ = what_;
        } else {
          result.what_ = summaryBuilder_.build();
        }
      }
      if (whatCase_ == 6) {
        if (logMessageBuilder_ == null) {
          result.what_ = what_;
        } else {
          result.what_ = logMessageBuilder_.build();
        }
      }
      if (whatCase_ == 7) {
        if (sessionLogBuilder_ == null) {
          result.what_ = what_;
        } else {
          result.what_ = sessionLogBuilder_.build();
        }
      }
      if (whatCase_ == 8) {
        if (taggedRunMetadataBuilder_ == null) {
          result.what_ = what_;
        } else {
          result.what_ = taggedRunMetadataBuilder_.build();
        }
      }
      if (whatCase_ == 9) {
        result.what_ = what_;
      }
      result.whatCase_ = whatCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Event) {
        return mergeFrom((Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Event other) {
      if (other == Event.getDefaultInstance()) return this;
      if (other.getWallTime() != 0D) {
        setWallTime(other.getWallTime());
      }
      if (other.getStep() != 0L) {
        setStep(other.getStep());
      }
      switch (other.getWhatCase()) {
        case FILE_VERSION: {
          whatCase_ = 3;
          what_ = other.what_;
          onChanged();
          break;
        }
        case GRAPH_DEF: {
          setGraphDef(other.getGraphDef());
          break;
        }
        case SUMMARY: {
          mergeSummary(other.getSummary());
          break;
        }
        case LOG_MESSAGE: {
          mergeLogMessage(other.getLogMessage());
          break;
        }
        case SESSION_LOG: {
          mergeSessionLog(other.getSessionLog());
          break;
        }
        case TAGGED_RUN_METADATA: {
          mergeTaggedRunMetadata(other.getTaggedRunMetadata());
          break;
        }
        case META_GRAPH_DEF: {
          setMetaGraphDef(other.getMetaGraphDef());
          break;
        }
        case WHAT_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int whatCase_ = 0;
    private java.lang.Object what_;
    public WhatCase
        getWhatCase() {
      return WhatCase.forNumber(
          whatCase_);
    }

    public Builder clearWhat() {
      whatCase_ = 0;
      what_ = null;
      onChanged();
      return this;
    }


    private double wallTime_ ;
    /**
     * <pre>
     * Timestamp of the event.
     * </pre>
     *
     * <code>optional double wall_time = 1;</code>
     */
    public double getWallTime() {
      return wallTime_;
    }
    /**
     * <pre>
     * Timestamp of the event.
     * </pre>
     *
     * <code>optional double wall_time = 1;</code>
     */
    public Builder setWallTime(double value) {
      
      wallTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of the event.
     * </pre>
     *
     * <code>optional double wall_time = 1;</code>
     */
    public Builder clearWallTime() {
      
      wallTime_ = 0D;
      onChanged();
      return this;
    }

    private long step_ ;
    /**
     * <pre>
     * Global step of the event.
     * </pre>
     *
     * <code>optional int64 step = 2;</code>
     */
    public long getStep() {
      return step_;
    }
    /**
     * <pre>
     * Global step of the event.
     * </pre>
     *
     * <code>optional int64 step = 2;</code>
     */
    public Builder setStep(long value) {
      
      step_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Global step of the event.
     * </pre>
     *
     * <code>optional int64 step = 2;</code>
     */
    public Builder clearStep() {
      
      step_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * An event file was started, with the specified version.
     * This is use to identify the contents of the record IO files
     * easily.  Current version is "brain.Event:2".  All versions
     * start with "brain.Event:".
     * </pre>
     *
     * <code>optional string file_version = 3;</code>
     */
    public java.lang.String getFileVersion() {
      java.lang.Object ref = "";
      if (whatCase_ == 3) {
        ref = what_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (whatCase_ == 3) {
          what_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * An event file was started, with the specified version.
     * This is use to identify the contents of the record IO files
     * easily.  Current version is "brain.Event:2".  All versions
     * start with "brain.Event:".
     * </pre>
     *
     * <code>optional string file_version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileVersionBytes() {
      java.lang.Object ref = "";
      if (whatCase_ == 3) {
        ref = what_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (whatCase_ == 3) {
          what_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * An event file was started, with the specified version.
     * This is use to identify the contents of the record IO files
     * easily.  Current version is "brain.Event:2".  All versions
     * start with "brain.Event:".
     * </pre>
     *
     * <code>optional string file_version = 3;</code>
     */
    public Builder setFileVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  whatCase_ = 3;
      what_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An event file was started, with the specified version.
     * This is use to identify the contents of the record IO files
     * easily.  Current version is "brain.Event:2".  All versions
     * start with "brain.Event:".
     * </pre>
     *
     * <code>optional string file_version = 3;</code>
     */
    public Builder clearFileVersion() {
      if (whatCase_ == 3) {
        whatCase_ = 0;
        what_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * An event file was started, with the specified version.
     * This is use to identify the contents of the record IO files
     * easily.  Current version is "brain.Event:2".  All versions
     * start with "brain.Event:".
     * </pre>
     *
     * <code>optional string file_version = 3;</code>
     */
    public Builder setFileVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      whatCase_ = 3;
      what_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * An encoded version of a GraphDef.
     * </pre>
     *
     * <code>optional bytes graph_def = 4;</code>
     */
    public com.google.protobuf.ByteString getGraphDef() {
      if (whatCase_ == 4) {
        return (com.google.protobuf.ByteString) what_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * An encoded version of a GraphDef.
     * </pre>
     *
     * <code>optional bytes graph_def = 4;</code>
     */
    public Builder setGraphDef(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  whatCase_ = 4;
      what_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An encoded version of a GraphDef.
     * </pre>
     *
     * <code>optional bytes graph_def = 4;</code>
     */
    public Builder clearGraphDef() {
      if (whatCase_ == 4) {
        whatCase_ = 0;
        what_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
      Summary, Summary.Builder, SummaryOrBuilder> summaryBuilder_;
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Summary getSummary() {
      if (summaryBuilder_ == null) {
        if (whatCase_ == 5) {
          return (Summary) what_;
        }
        return Summary.getDefaultInstance();
      } else {
        if (whatCase_ == 5) {
          return summaryBuilder_.getMessage();
        }
        return Summary.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Builder setSummary(Summary value) {
      if (summaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        what_ = value;
        onChanged();
      } else {
        summaryBuilder_.setMessage(value);
      }
      whatCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Builder setSummary(
        Summary.Builder builderForValue) {
      if (summaryBuilder_ == null) {
        what_ = builderForValue.build();
        onChanged();
      } else {
        summaryBuilder_.setMessage(builderForValue.build());
      }
      whatCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Builder mergeSummary(Summary value) {
      if (summaryBuilder_ == null) {
        if (whatCase_ == 5 &&
            what_ != Summary.getDefaultInstance()) {
          what_ = Summary.newBuilder((Summary) what_)
              .mergeFrom(value).buildPartial();
        } else {
          what_ = value;
        }
        onChanged();
      } else {
        if (whatCase_ == 5) {
          summaryBuilder_.mergeFrom(value);
        }
        summaryBuilder_.setMessage(value);
      }
      whatCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Builder clearSummary() {
      if (summaryBuilder_ == null) {
        if (whatCase_ == 5) {
          whatCase_ = 0;
          what_ = null;
          onChanged();
        }
      } else {
        if (whatCase_ == 5) {
          whatCase_ = 0;
          what_ = null;
        }
        summaryBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public Summary.Builder getSummaryBuilder() {
      return getSummaryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    public SummaryOrBuilder getSummaryOrBuilder() {
      if ((whatCase_ == 5) && (summaryBuilder_ != null)) {
        return summaryBuilder_.getMessageOrBuilder();
      } else {
        if (whatCase_ == 5) {
          return (Summary) what_;
        }
        return Summary.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * A summary was generated.
     * </pre>
     *
     * <code>optional .tensorboard.Summary summary = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
      Summary, Summary.Builder, SummaryOrBuilder>
        getSummaryFieldBuilder() {
      if (summaryBuilder_ == null) {
        if (!(whatCase_ == 5)) {
          what_ = Summary.getDefaultInstance();
        }
        summaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
          Summary, Summary.Builder, SummaryOrBuilder>(
                (Summary) what_,
                getParentForChildren(),
                isClean());
        what_ = null;
      }
      whatCase_ = 5;
      onChanged();;
      return summaryBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
      LogMessage, LogMessage.Builder, LogMessageOrBuilder> logMessageBuilder_;
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public LogMessage getLogMessage() {
      if (logMessageBuilder_ == null) {
        if (whatCase_ == 6) {
          return (LogMessage) what_;
        }
        return LogMessage.getDefaultInstance();
      } else {
        if (whatCase_ == 6) {
          return logMessageBuilder_.getMessage();
        }
        return LogMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public Builder setLogMessage(LogMessage value) {
      if (logMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        what_ = value;
        onChanged();
      } else {
        logMessageBuilder_.setMessage(value);
      }
      whatCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public Builder setLogMessage(
        LogMessage.Builder builderForValue) {
      if (logMessageBuilder_ == null) {
        what_ = builderForValue.build();
        onChanged();
      } else {
        logMessageBuilder_.setMessage(builderForValue.build());
      }
      whatCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public Builder mergeLogMessage(LogMessage value) {
      if (logMessageBuilder_ == null) {
        if (whatCase_ == 6 &&
            what_ != LogMessage.getDefaultInstance()) {
          what_ = LogMessage.newBuilder((LogMessage) what_)
              .mergeFrom(value).buildPartial();
        } else {
          what_ = value;
        }
        onChanged();
      } else {
        if (whatCase_ == 6) {
          logMessageBuilder_.mergeFrom(value);
        }
        logMessageBuilder_.setMessage(value);
      }
      whatCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public Builder clearLogMessage() {
      if (logMessageBuilder_ == null) {
        if (whatCase_ == 6) {
          whatCase_ = 0;
          what_ = null;
          onChanged();
        }
      } else {
        if (whatCase_ == 6) {
          whatCase_ = 0;
          what_ = null;
        }
        logMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public LogMessage.Builder getLogMessageBuilder() {
      return getLogMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    public LogMessageOrBuilder getLogMessageOrBuilder() {
      if ((whatCase_ == 6) && (logMessageBuilder_ != null)) {
        return logMessageBuilder_.getMessageOrBuilder();
      } else {
        if (whatCase_ == 6) {
          return (LogMessage) what_;
        }
        return LogMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The user output a log message. Not all messages are logged, only ones
     * generated via the Python tensorboard_logging module.
     * </pre>
     *
     * <code>optional .tensorboard.LogMessage log_message = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
      LogMessage, LogMessage.Builder, LogMessageOrBuilder>
        getLogMessageFieldBuilder() {
      if (logMessageBuilder_ == null) {
        if (!(whatCase_ == 6)) {
          what_ = LogMessage.getDefaultInstance();
        }
        logMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
          LogMessage, LogMessage.Builder, LogMessageOrBuilder>(
                (LogMessage) what_,
                getParentForChildren(),
                isClean());
        what_ = null;
      }
      whatCase_ = 6;
      onChanged();;
      return logMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
      SessionLog, SessionLog.Builder, SessionLogOrBuilder> sessionLogBuilder_;
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public SessionLog getSessionLog() {
      if (sessionLogBuilder_ == null) {
        if (whatCase_ == 7) {
          return (SessionLog) what_;
        }
        return SessionLog.getDefaultInstance();
      } else {
        if (whatCase_ == 7) {
          return sessionLogBuilder_.getMessage();
        }
        return SessionLog.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public Builder setSessionLog(SessionLog value) {
      if (sessionLogBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        what_ = value;
        onChanged();
      } else {
        sessionLogBuilder_.setMessage(value);
      }
      whatCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public Builder setSessionLog(
        SessionLog.Builder builderForValue) {
      if (sessionLogBuilder_ == null) {
        what_ = builderForValue.build();
        onChanged();
      } else {
        sessionLogBuilder_.setMessage(builderForValue.build());
      }
      whatCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public Builder mergeSessionLog(SessionLog value) {
      if (sessionLogBuilder_ == null) {
        if (whatCase_ == 7 &&
            what_ != SessionLog.getDefaultInstance()) {
          what_ = SessionLog.newBuilder((SessionLog) what_)
              .mergeFrom(value).buildPartial();
        } else {
          what_ = value;
        }
        onChanged();
      } else {
        if (whatCase_ == 7) {
          sessionLogBuilder_.mergeFrom(value);
        }
        sessionLogBuilder_.setMessage(value);
      }
      whatCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public Builder clearSessionLog() {
      if (sessionLogBuilder_ == null) {
        if (whatCase_ == 7) {
          whatCase_ = 0;
          what_ = null;
          onChanged();
        }
      } else {
        if (whatCase_ == 7) {
          whatCase_ = 0;
          what_ = null;
        }
        sessionLogBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public SessionLog.Builder getSessionLogBuilder() {
      return getSessionLogFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    public SessionLogOrBuilder getSessionLogOrBuilder() {
      if ((whatCase_ == 7) && (sessionLogBuilder_ != null)) {
        return sessionLogBuilder_.getMessageOrBuilder();
      } else {
        if (whatCase_ == 7) {
          return (SessionLog) what_;
        }
        return SessionLog.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The state of the session which can be used for restarting after crashes.
     * </pre>
     *
     * <code>optional .tensorboard.SessionLog session_log = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
      SessionLog, SessionLog.Builder, SessionLogOrBuilder>
        getSessionLogFieldBuilder() {
      if (sessionLogBuilder_ == null) {
        if (!(whatCase_ == 7)) {
          what_ = SessionLog.getDefaultInstance();
        }
        sessionLogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
          SessionLog, SessionLog.Builder, SessionLogOrBuilder>(
                (SessionLog) what_,
                getParentForChildren(),
                isClean());
        what_ = null;
      }
      whatCase_ = 7;
      onChanged();;
      return sessionLogBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
      TaggedRunMetadata, TaggedRunMetadata.Builder, TaggedRunMetadataOrBuilder> taggedRunMetadataBuilder_;
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public TaggedRunMetadata getTaggedRunMetadata() {
      if (taggedRunMetadataBuilder_ == null) {
        if (whatCase_ == 8) {
          return (TaggedRunMetadata) what_;
        }
        return TaggedRunMetadata.getDefaultInstance();
      } else {
        if (whatCase_ == 8) {
          return taggedRunMetadataBuilder_.getMessage();
        }
        return TaggedRunMetadata.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public Builder setTaggedRunMetadata(TaggedRunMetadata value) {
      if (taggedRunMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        what_ = value;
        onChanged();
      } else {
        taggedRunMetadataBuilder_.setMessage(value);
      }
      whatCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public Builder setTaggedRunMetadata(
        TaggedRunMetadata.Builder builderForValue) {
      if (taggedRunMetadataBuilder_ == null) {
        what_ = builderForValue.build();
        onChanged();
      } else {
        taggedRunMetadataBuilder_.setMessage(builderForValue.build());
      }
      whatCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public Builder mergeTaggedRunMetadata(TaggedRunMetadata value) {
      if (taggedRunMetadataBuilder_ == null) {
        if (whatCase_ == 8 &&
            what_ != TaggedRunMetadata.getDefaultInstance()) {
          what_ = TaggedRunMetadata.newBuilder((TaggedRunMetadata) what_)
              .mergeFrom(value).buildPartial();
        } else {
          what_ = value;
        }
        onChanged();
      } else {
        if (whatCase_ == 8) {
          taggedRunMetadataBuilder_.mergeFrom(value);
        }
        taggedRunMetadataBuilder_.setMessage(value);
      }
      whatCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public Builder clearTaggedRunMetadata() {
      if (taggedRunMetadataBuilder_ == null) {
        if (whatCase_ == 8) {
          whatCase_ = 0;
          what_ = null;
          onChanged();
        }
      } else {
        if (whatCase_ == 8) {
          whatCase_ = 0;
          what_ = null;
        }
        taggedRunMetadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public TaggedRunMetadata.Builder getTaggedRunMetadataBuilder() {
      return getTaggedRunMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    public TaggedRunMetadataOrBuilder getTaggedRunMetadataOrBuilder() {
      if ((whatCase_ == 8) && (taggedRunMetadataBuilder_ != null)) {
        return taggedRunMetadataBuilder_.getMessageOrBuilder();
      } else {
        if (whatCase_ == 8) {
          return (TaggedRunMetadata) what_;
        }
        return TaggedRunMetadata.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The metadata returned by running a session.run() call.
     * </pre>
     *
     * <code>optional .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
      TaggedRunMetadata, TaggedRunMetadata.Builder, TaggedRunMetadataOrBuilder>
        getTaggedRunMetadataFieldBuilder() {
      if (taggedRunMetadataBuilder_ == null) {
        if (!(whatCase_ == 8)) {
          what_ = TaggedRunMetadata.getDefaultInstance();
        }
        taggedRunMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
          TaggedRunMetadata, TaggedRunMetadata.Builder, TaggedRunMetadataOrBuilder>(
                (TaggedRunMetadata) what_,
                getParentForChildren(),
                isClean());
        what_ = null;
      }
      whatCase_ = 8;
      onChanged();;
      return taggedRunMetadataBuilder_;
    }

    /**
     * <pre>
     * An encoded version of a MetaGraphDef.
     * </pre>
     *
     * <code>optional bytes meta_graph_def = 9;</code>
     */
    public com.google.protobuf.ByteString getMetaGraphDef() {
      if (whatCase_ == 9) {
        return (com.google.protobuf.ByteString) what_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * An encoded version of a MetaGraphDef.
     * </pre>
     *
     * <code>optional bytes meta_graph_def = 9;</code>
     */
    public Builder setMetaGraphDef(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  whatCase_ = 9;
      what_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An encoded version of a MetaGraphDef.
     * </pre>
     *
     * <code>optional bytes meta_graph_def = 9;</code>
     */
    public Builder clearMetaGraphDef() {
      if (whatCase_ == 9) {
        whatCase_ = 0;
        what_ = null;
        onChanged();
      }
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorboard.Event)
  }

  // @@protoc_insertion_point(class_scope:tensorboard.Event)
  private static final Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Event();
  }

  public static Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  public Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

