name: 'Mac Friesian Python ExampleTest Tf2 Spark3.1'
description: 'Mac Friesian Python ExampleTest Tf2 Spark3.1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source ~/.bash_profile
        export SPARK_HOME=/opt/work/spark-3.4.1
        PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.4.1
        cd -
        source python/friesian/dev/prepare_env.sh
        source activate py37-tf2
        pip uninstall -y bigdl-dllib bigdl-orca bigdl-chronos bigdl-orca-spark3 bigdl-dllib-spark3 bigdl-chronos-spark3  pyspark
        
        pip install pyspark==3.4.1
        echo "Running py37 tests"
        cd python/friesian/dev/test
        gsed -i "s/sed/gsed/g" run-example-tests-tf2.6.0.sh
        bash run-example-tests-tf2.6.0.sh

        conda deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        
