name: 'Run Orca Python Ray Ctx Py37 Spark3'
description: 'Run Orca Python Ray Ctx Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export _JAVA_OPTIONS="-XX:MaxPermSize=3G -Xmx10G"
        export MAVEN_OPTS="-XX:ReservedCodeCacheSize=512m -XX:MaxPermSize=3G -Xmx10G"
        export http_proxy="http://child-prc.intel.com:913/"
        export https_proxy="http://child-prc.intel.com:913/"
        
        export JAVA_HOME=/opt/work/jdk8
        export CLASSPATH=.:${JAVA_HOME}/lib:${JAVA_HOME}/jre/lib:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/lib/dt.jar
        export PATH=${JAVA_HOME}/bin/:${JAVA_HOME}/jre/bin:${PATH}
        export PATH=/opt/work/apache-maven-3.6.3/bin:$PATH 

        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib-spark3 bigdl-orca-spark3 bigdl-chronos-spark3 pyspark bigdl-orca bigdl-dllib bigdl-chronos bigdl-tf bigdl-math
        echo "### start ray_ctx tests"

        pip install --upgrade pip

        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3[ray]
        pip install ray==1.11.0

        # This machine does not support GONDOLIN pip mirror
        pip install tensorflow==2.9.0
        pip install torch==1.7.1
        pip install torchvision==0.8.2
        pip install torchmetrics==0.10.0
        pip install tqdm
        pip install pyarrow
        pip install pandas

        chmod a+x python/orca/dev/test/run-pytests-ray-ctx.sh
        python/orca/dev/test/run-pytests-ray-ctx.sh

        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}