// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package serialization;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BigDLModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.BigDLModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    java.util.List<serialization.Model.BigDLModel> 
        getSubModulesList();
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    serialization.Model.BigDLModel getSubModules(int index);
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    int getSubModulesCount();
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    java.util.List<? extends serialization.Model.BigDLModelOrBuilder> 
        getSubModulesOrBuilderList();
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    serialization.Model.BigDLModelOrBuilder getSubModulesOrBuilder(
        int index);

    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    boolean hasWeight();
    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    serialization.Model.BigDLTensor getWeight();
    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    serialization.Model.BigDLTensorOrBuilder getWeightOrBuilder();

    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    boolean hasBias();
    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    serialization.Model.BigDLTensor getBias();
    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    serialization.Model.BigDLTensorOrBuilder getBiasOrBuilder();

    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    java.util.List<java.lang.Double> getModuleParamsList();
    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    int getModuleParamsCount();
    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    double getModuleParams(int index);

    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getTopsList();
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    int getTopsCount();
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    java.lang.String getTops(int index);
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    com.google.protobuf.ByteString
        getTopsBytes(int index);

    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getBottomsList();
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    int getBottomsCount();
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    java.lang.String getBottoms(int index);
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    com.google.protobuf.ByteString
        getBottomsBytes(int index);

    /**
     * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
     *
     * <pre>
     *module type
     * </pre>
     */
    boolean hasModuleType();
    /**
     * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
     *
     * <pre>
     *module type
     * </pre>
     */
    serialization.Model.BigDLModel.ModuleType getModuleType();
  }
  /**
   * Protobuf type {@code serialization.BigDLModel}
   */
  public static final class BigDLModel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.BigDLModel)
      BigDLModelOrBuilder {
    // Use BigDLModel.newBuilder() to construct.
    private BigDLModel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BigDLModel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BigDLModel defaultInstance;
    public static BigDLModel getDefaultInstance() {
      return defaultInstance;
    }

    public BigDLModel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BigDLModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                subModules_ = new java.util.ArrayList<serialization.Model.BigDLModel>();
                mutable_bitField0_ |= 0x00000002;
              }
              subModules_.add(input.readMessage(serialization.Model.BigDLModel.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              serialization.Model.BigDLTensor.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = weight_.toBuilder();
              }
              weight_ = input.readMessage(serialization.Model.BigDLTensor.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(weight_);
                weight_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              serialization.Model.BigDLTensor.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = bias_.toBuilder();
              }
              bias_ = input.readMessage(serialization.Model.BigDLTensor.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bias_);
                bias_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                moduleParams_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              moduleParams_.add(input.readDouble());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                moduleParams_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                moduleParams_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                tops_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              tops_.add(bs);
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                bottoms_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              bottoms_.add(bs);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              serialization.Model.BigDLModel.ModuleType value = serialization.Model.BigDLModel.ModuleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                moduleType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          subModules_ = java.util.Collections.unmodifiableList(subModules_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          moduleParams_ = java.util.Collections.unmodifiableList(moduleParams_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          tops_ = tops_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          bottoms_ = bottoms_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serialization.Model.internal_static_serialization_BigDLModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serialization.Model.internal_static_serialization_BigDLModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serialization.Model.BigDLModel.class, serialization.Model.BigDLModel.Builder.class);
    }

    public static com.google.protobuf.Parser<BigDLModel> PARSER =
        new com.google.protobuf.AbstractParser<BigDLModel>() {
      public BigDLModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BigDLModel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BigDLModel> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code serialization.BigDLModel.ModuleType}
     */
    public enum ModuleType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LINEAR = 1;</code>
       */
      LINEAR(0, 1),
      /**
       * <code>SEQUENTIAL = 2;</code>
       */
      SEQUENTIAL(1, 2),
      ;

      /**
       * <code>LINEAR = 1;</code>
       */
      public static final int LINEAR_VALUE = 1;
      /**
       * <code>SEQUENTIAL = 2;</code>
       */
      public static final int SEQUENTIAL_VALUE = 2;


      public final int getNumber() { return value; }

      public static ModuleType valueOf(int value) {
        switch (value) {
          case 1: return LINEAR;
          case 2: return SEQUENTIAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ModuleType>() {
              public ModuleType findValueByNumber(int number) {
                return ModuleType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return serialization.Model.BigDLModel.getDescriptor().getEnumTypes().get(0);
      }

      private static final ModuleType[] VALUES = values();

      public static ModuleType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ModuleType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:serialization.BigDLModel.ModuleType)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *model name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBMODULES_FIELD_NUMBER = 2;
    private java.util.List<serialization.Model.BigDLModel> subModules_;
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    public java.util.List<serialization.Model.BigDLModel> getSubModulesList() {
      return subModules_;
    }
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    public java.util.List<? extends serialization.Model.BigDLModelOrBuilder> 
        getSubModulesOrBuilderList() {
      return subModules_;
    }
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    public int getSubModulesCount() {
      return subModules_.size();
    }
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    public serialization.Model.BigDLModel getSubModules(int index) {
      return subModules_.get(index);
    }
    /**
     * <code>repeated .serialization.BigDLModel subModules = 2;</code>
     *
     * <pre>
     * sub modules
     * </pre>
     */
    public serialization.Model.BigDLModelOrBuilder getSubModulesOrBuilder(
        int index) {
      return subModules_.get(index);
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private serialization.Model.BigDLTensor weight_;
    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    public serialization.Model.BigDLTensor getWeight() {
      return weight_;
    }
    /**
     * <code>optional .serialization.BigDLTensor weight = 3;</code>
     *
     * <pre>
     * double weight for each layer
     * </pre>
     */
    public serialization.Model.BigDLTensorOrBuilder getWeightOrBuilder() {
      return weight_;
    }

    public static final int BIAS_FIELD_NUMBER = 4;
    private serialization.Model.BigDLTensor bias_;
    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    public boolean hasBias() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    public serialization.Model.BigDLTensor getBias() {
      return bias_;
    }
    /**
     * <code>optional .serialization.BigDLTensor bias = 4;</code>
     *
     * <pre>
     * double bias for each layer
     * </pre>
     */
    public serialization.Model.BigDLTensorOrBuilder getBiasOrBuilder() {
      return bias_;
    }

    public static final int MODULEPARAMS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Double> moduleParams_;
    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public java.util.List<java.lang.Double>
        getModuleParamsList() {
      return moduleParams_;
    }
    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public int getModuleParamsCount() {
      return moduleParams_.size();
    }
    /**
     * <code>repeated double moduleParams = 5;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public double getModuleParams(int index) {
      return moduleParams_.get(index);
    }

    public static final int TOPS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList tops_;
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getTopsList() {
      return tops_;
    }
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public int getTopsCount() {
      return tops_.size();
    }
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public java.lang.String getTops(int index) {
      return tops_.get(index);
    }
    /**
     * <code>repeated string tops = 6;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTopsBytes(int index) {
      return tops_.getByteString(index);
    }

    public static final int BOTTOMS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList bottoms_;
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getBottomsList() {
      return bottoms_;
    }
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public int getBottomsCount() {
      return bottoms_.size();
    }
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public java.lang.String getBottoms(int index) {
      return bottoms_.get(index);
    }
    /**
     * <code>repeated string bottoms = 7;</code>
     *
     * <pre>
     *module layer construct params
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBottomsBytes(int index) {
      return bottoms_.getByteString(index);
    }

    public static final int MODULETYPE_FIELD_NUMBER = 8;
    private serialization.Model.BigDLModel.ModuleType moduleType_;
    /**
     * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
     *
     * <pre>
     *module type
     * </pre>
     */
    public boolean hasModuleType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
     *
     * <pre>
     *module type
     * </pre>
     */
    public serialization.Model.BigDLModel.ModuleType getModuleType() {
      return moduleType_;
    }

    private void initFields() {
      name_ = "";
      subModules_ = java.util.Collections.emptyList();
      weight_ = serialization.Model.BigDLTensor.getDefaultInstance();
      bias_ = serialization.Model.BigDLTensor.getDefaultInstance();
      moduleParams_ = java.util.Collections.emptyList();
      tops_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bottoms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      moduleType_ = serialization.Model.BigDLModel.ModuleType.LINEAR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasModuleType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSubModulesCount(); i++) {
        if (!getSubModules(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < subModules_.size(); i++) {
        output.writeMessage(2, subModules_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, weight_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, bias_);
      }
      for (int i = 0; i < moduleParams_.size(); i++) {
        output.writeDouble(5, moduleParams_.get(i));
      }
      for (int i = 0; i < tops_.size(); i++) {
        output.writeBytes(6, tops_.getByteString(i));
      }
      for (int i = 0; i < bottoms_.size(); i++) {
        output.writeBytes(7, bottoms_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(8, moduleType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < subModules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subModules_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, weight_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, bias_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getModuleParamsList().size();
        size += dataSize;
        size += 1 * getModuleParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tops_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tops_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTopsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bottoms_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(bottoms_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBottomsList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, moduleType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serialization.Model.BigDLModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Model.BigDLModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Model.BigDLModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Model.BigDLModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Model.BigDLModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Model.BigDLModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serialization.Model.BigDLModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serialization.Model.BigDLModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serialization.Model.BigDLModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Model.BigDLModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serialization.Model.BigDLModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.BigDLModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.BigDLModel)
        serialization.Model.BigDLModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serialization.Model.internal_static_serialization_BigDLModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serialization.Model.internal_static_serialization_BigDLModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serialization.Model.BigDLModel.class, serialization.Model.BigDLModel.Builder.class);
      }

      // Construct using serialization.Model.BigDLModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSubModulesFieldBuilder();
          getWeightFieldBuilder();
          getBiasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (subModulesBuilder_ == null) {
          subModules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          subModulesBuilder_.clear();
        }
        if (weightBuilder_ == null) {
          weight_ = serialization.Model.BigDLTensor.getDefaultInstance();
        } else {
          weightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (biasBuilder_ == null) {
          bias_ = serialization.Model.BigDLTensor.getDefaultInstance();
        } else {
          biasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        moduleParams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        tops_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        bottoms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        moduleType_ = serialization.Model.BigDLModel.ModuleType.LINEAR;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serialization.Model.internal_static_serialization_BigDLModel_descriptor;
      }

      public serialization.Model.BigDLModel getDefaultInstanceForType() {
        return serialization.Model.BigDLModel.getDefaultInstance();
      }

      public serialization.Model.BigDLModel build() {
        serialization.Model.BigDLModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serialization.Model.BigDLModel buildPartial() {
        serialization.Model.BigDLModel result = new serialization.Model.BigDLModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (subModulesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            subModules_ = java.util.Collections.unmodifiableList(subModules_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subModules_ = subModules_;
        } else {
          result.subModules_ = subModulesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (weightBuilder_ == null) {
          result.weight_ = weight_;
        } else {
          result.weight_ = weightBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (biasBuilder_ == null) {
          result.bias_ = bias_;
        } else {
          result.bias_ = biasBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          moduleParams_ = java.util.Collections.unmodifiableList(moduleParams_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.moduleParams_ = moduleParams_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          tops_ = tops_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.tops_ = tops_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          bottoms_ = bottoms_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.bottoms_ = bottoms_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000008;
        }
        result.moduleType_ = moduleType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serialization.Model.BigDLModel) {
          return mergeFrom((serialization.Model.BigDLModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serialization.Model.BigDLModel other) {
        if (other == serialization.Model.BigDLModel.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (subModulesBuilder_ == null) {
          if (!other.subModules_.isEmpty()) {
            if (subModules_.isEmpty()) {
              subModules_ = other.subModules_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubModulesIsMutable();
              subModules_.addAll(other.subModules_);
            }
            onChanged();
          }
        } else {
          if (!other.subModules_.isEmpty()) {
            if (subModulesBuilder_.isEmpty()) {
              subModulesBuilder_.dispose();
              subModulesBuilder_ = null;
              subModules_ = other.subModules_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subModulesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSubModulesFieldBuilder() : null;
            } else {
              subModulesBuilder_.addAllMessages(other.subModules_);
            }
          }
        }
        if (other.hasWeight()) {
          mergeWeight(other.getWeight());
        }
        if (other.hasBias()) {
          mergeBias(other.getBias());
        }
        if (!other.moduleParams_.isEmpty()) {
          if (moduleParams_.isEmpty()) {
            moduleParams_ = other.moduleParams_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureModuleParamsIsMutable();
            moduleParams_.addAll(other.moduleParams_);
          }
          onChanged();
        }
        if (!other.tops_.isEmpty()) {
          if (tops_.isEmpty()) {
            tops_ = other.tops_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTopsIsMutable();
            tops_.addAll(other.tops_);
          }
          onChanged();
        }
        if (!other.bottoms_.isEmpty()) {
          if (bottoms_.isEmpty()) {
            bottoms_ = other.bottoms_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureBottomsIsMutable();
            bottoms_.addAll(other.bottoms_);
          }
          onChanged();
        }
        if (other.hasModuleType()) {
          setModuleType(other.getModuleType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModuleType()) {
          
          return false;
        }
        for (int i = 0; i < getSubModulesCount(); i++) {
          if (!getSubModules(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serialization.Model.BigDLModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serialization.Model.BigDLModel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *model name
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<serialization.Model.BigDLModel> subModules_ =
        java.util.Collections.emptyList();
      private void ensureSubModulesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          subModules_ = new java.util.ArrayList<serialization.Model.BigDLModel>(subModules_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          serialization.Model.BigDLModel, serialization.Model.BigDLModel.Builder, serialization.Model.BigDLModelOrBuilder> subModulesBuilder_;

      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public java.util.List<serialization.Model.BigDLModel> getSubModulesList() {
        if (subModulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subModules_);
        } else {
          return subModulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public int getSubModulesCount() {
        if (subModulesBuilder_ == null) {
          return subModules_.size();
        } else {
          return subModulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public serialization.Model.BigDLModel getSubModules(int index) {
        if (subModulesBuilder_ == null) {
          return subModules_.get(index);
        } else {
          return subModulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder setSubModules(
          int index, serialization.Model.BigDLModel value) {
        if (subModulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubModulesIsMutable();
          subModules_.set(index, value);
          onChanged();
        } else {
          subModulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder setSubModules(
          int index, serialization.Model.BigDLModel.Builder builderForValue) {
        if (subModulesBuilder_ == null) {
          ensureSubModulesIsMutable();
          subModules_.set(index, builderForValue.build());
          onChanged();
        } else {
          subModulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder addSubModules(serialization.Model.BigDLModel value) {
        if (subModulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubModulesIsMutable();
          subModules_.add(value);
          onChanged();
        } else {
          subModulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder addSubModules(
          int index, serialization.Model.BigDLModel value) {
        if (subModulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubModulesIsMutable();
          subModules_.add(index, value);
          onChanged();
        } else {
          subModulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder addSubModules(
          serialization.Model.BigDLModel.Builder builderForValue) {
        if (subModulesBuilder_ == null) {
          ensureSubModulesIsMutable();
          subModules_.add(builderForValue.build());
          onChanged();
        } else {
          subModulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder addSubModules(
          int index, serialization.Model.BigDLModel.Builder builderForValue) {
        if (subModulesBuilder_ == null) {
          ensureSubModulesIsMutable();
          subModules_.add(index, builderForValue.build());
          onChanged();
        } else {
          subModulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder addAllSubModules(
          java.lang.Iterable<? extends serialization.Model.BigDLModel> values) {
        if (subModulesBuilder_ == null) {
          ensureSubModulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subModules_);
          onChanged();
        } else {
          subModulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder clearSubModules() {
        if (subModulesBuilder_ == null) {
          subModules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subModulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public Builder removeSubModules(int index) {
        if (subModulesBuilder_ == null) {
          ensureSubModulesIsMutable();
          subModules_.remove(index);
          onChanged();
        } else {
          subModulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public serialization.Model.BigDLModel.Builder getSubModulesBuilder(
          int index) {
        return getSubModulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public serialization.Model.BigDLModelOrBuilder getSubModulesOrBuilder(
          int index) {
        if (subModulesBuilder_ == null) {
          return subModules_.get(index);  } else {
          return subModulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public java.util.List<? extends serialization.Model.BigDLModelOrBuilder> 
           getSubModulesOrBuilderList() {
        if (subModulesBuilder_ != null) {
          return subModulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subModules_);
        }
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public serialization.Model.BigDLModel.Builder addSubModulesBuilder() {
        return getSubModulesFieldBuilder().addBuilder(
            serialization.Model.BigDLModel.getDefaultInstance());
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public serialization.Model.BigDLModel.Builder addSubModulesBuilder(
          int index) {
        return getSubModulesFieldBuilder().addBuilder(
            index, serialization.Model.BigDLModel.getDefaultInstance());
      }
      /**
       * <code>repeated .serialization.BigDLModel subModules = 2;</code>
       *
       * <pre>
       * sub modules
       * </pre>
       */
      public java.util.List<serialization.Model.BigDLModel.Builder> 
           getSubModulesBuilderList() {
        return getSubModulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          serialization.Model.BigDLModel, serialization.Model.BigDLModel.Builder, serialization.Model.BigDLModelOrBuilder> 
          getSubModulesFieldBuilder() {
        if (subModulesBuilder_ == null) {
          subModulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              serialization.Model.BigDLModel, serialization.Model.BigDLModel.Builder, serialization.Model.BigDLModelOrBuilder>(
                  subModules_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          subModules_ = null;
        }
        return subModulesBuilder_;
      }

      private serialization.Model.BigDLTensor weight_ = serialization.Model.BigDLTensor.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder> weightBuilder_;
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensor getWeight() {
        if (weightBuilder_ == null) {
          return weight_;
        } else {
          return weightBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public Builder setWeight(serialization.Model.BigDLTensor value) {
        if (weightBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weight_ = value;
          onChanged();
        } else {
          weightBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public Builder setWeight(
          serialization.Model.BigDLTensor.Builder builderForValue) {
        if (weightBuilder_ == null) {
          weight_ = builderForValue.build();
          onChanged();
        } else {
          weightBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public Builder mergeWeight(serialization.Model.BigDLTensor value) {
        if (weightBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              weight_ != serialization.Model.BigDLTensor.getDefaultInstance()) {
            weight_ =
              serialization.Model.BigDLTensor.newBuilder(weight_).mergeFrom(value).buildPartial();
          } else {
            weight_ = value;
          }
          onChanged();
        } else {
          weightBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public Builder clearWeight() {
        if (weightBuilder_ == null) {
          weight_ = serialization.Model.BigDLTensor.getDefaultInstance();
          onChanged();
        } else {
          weightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensor.Builder getWeightBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWeightFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensorOrBuilder getWeightOrBuilder() {
        if (weightBuilder_ != null) {
          return weightBuilder_.getMessageOrBuilder();
        } else {
          return weight_;
        }
      }
      /**
       * <code>optional .serialization.BigDLTensor weight = 3;</code>
       *
       * <pre>
       * double weight for each layer
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder> 
          getWeightFieldBuilder() {
        if (weightBuilder_ == null) {
          weightBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder>(
                  getWeight(),
                  getParentForChildren(),
                  isClean());
          weight_ = null;
        }
        return weightBuilder_;
      }

      private serialization.Model.BigDLTensor bias_ = serialization.Model.BigDLTensor.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder> biasBuilder_;
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public boolean hasBias() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensor getBias() {
        if (biasBuilder_ == null) {
          return bias_;
        } else {
          return biasBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public Builder setBias(serialization.Model.BigDLTensor value) {
        if (biasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bias_ = value;
          onChanged();
        } else {
          biasBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public Builder setBias(
          serialization.Model.BigDLTensor.Builder builderForValue) {
        if (biasBuilder_ == null) {
          bias_ = builderForValue.build();
          onChanged();
        } else {
          biasBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public Builder mergeBias(serialization.Model.BigDLTensor value) {
        if (biasBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              bias_ != serialization.Model.BigDLTensor.getDefaultInstance()) {
            bias_ =
              serialization.Model.BigDLTensor.newBuilder(bias_).mergeFrom(value).buildPartial();
          } else {
            bias_ = value;
          }
          onChanged();
        } else {
          biasBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public Builder clearBias() {
        if (biasBuilder_ == null) {
          bias_ = serialization.Model.BigDLTensor.getDefaultInstance();
          onChanged();
        } else {
          biasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensor.Builder getBiasBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBiasFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      public serialization.Model.BigDLTensorOrBuilder getBiasOrBuilder() {
        if (biasBuilder_ != null) {
          return biasBuilder_.getMessageOrBuilder();
        } else {
          return bias_;
        }
      }
      /**
       * <code>optional .serialization.BigDLTensor bias = 4;</code>
       *
       * <pre>
       * double bias for each layer
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder> 
          getBiasFieldBuilder() {
        if (biasBuilder_ == null) {
          biasBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              serialization.Model.BigDLTensor, serialization.Model.BigDLTensor.Builder, serialization.Model.BigDLTensorOrBuilder>(
                  getBias(),
                  getParentForChildren(),
                  isClean());
          bias_ = null;
        }
        return biasBuilder_;
      }

      private java.util.List<java.lang.Double> moduleParams_ = java.util.Collections.emptyList();
      private void ensureModuleParamsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          moduleParams_ = new java.util.ArrayList<java.lang.Double>(moduleParams_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public java.util.List<java.lang.Double>
          getModuleParamsList() {
        return java.util.Collections.unmodifiableList(moduleParams_);
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public int getModuleParamsCount() {
        return moduleParams_.size();
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public double getModuleParams(int index) {
        return moduleParams_.get(index);
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder setModuleParams(
          int index, double value) {
        ensureModuleParamsIsMutable();
        moduleParams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addModuleParams(double value) {
        ensureModuleParamsIsMutable();
        moduleParams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addAllModuleParams(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureModuleParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, moduleParams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double moduleParams = 5;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder clearModuleParams() {
        moduleParams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList tops_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTopsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          tops_ = new com.google.protobuf.LazyStringArrayList(tops_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getTopsList() {
        return tops_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public int getTopsCount() {
        return tops_.size();
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public java.lang.String getTops(int index) {
        return tops_.get(index);
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTopsBytes(int index) {
        return tops_.getByteString(index);
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder setTops(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopsIsMutable();
        tops_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addTops(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopsIsMutable();
        tops_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addAllTops(
          java.lang.Iterable<java.lang.String> values) {
        ensureTopsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tops_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder clearTops() {
        tops_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tops = 6;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addTopsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopsIsMutable();
        tops_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList bottoms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBottomsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          bottoms_ = new com.google.protobuf.LazyStringArrayList(bottoms_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getBottomsList() {
        return bottoms_.getUnmodifiableView();
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public int getBottomsCount() {
        return bottoms_.size();
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public java.lang.String getBottoms(int index) {
        return bottoms_.get(index);
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBottomsBytes(int index) {
        return bottoms_.getByteString(index);
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder setBottoms(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBottomsIsMutable();
        bottoms_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addBottoms(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBottomsIsMutable();
        bottoms_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addAllBottoms(
          java.lang.Iterable<java.lang.String> values) {
        ensureBottomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bottoms_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder clearBottoms() {
        bottoms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bottoms = 7;</code>
       *
       * <pre>
       *module layer construct params
       * </pre>
       */
      public Builder addBottomsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBottomsIsMutable();
        bottoms_.add(value);
        onChanged();
        return this;
      }

      private serialization.Model.BigDLModel.ModuleType moduleType_ = serialization.Model.BigDLModel.ModuleType.LINEAR;
      /**
       * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
       *
       * <pre>
       *module type
       * </pre>
       */
      public boolean hasModuleType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
       *
       * <pre>
       *module type
       * </pre>
       */
      public serialization.Model.BigDLModel.ModuleType getModuleType() {
        return moduleType_;
      }
      /**
       * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
       *
       * <pre>
       *module type
       * </pre>
       */
      public Builder setModuleType(serialization.Model.BigDLModel.ModuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        moduleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .serialization.BigDLModel.ModuleType moduleType = 8;</code>
       *
       * <pre>
       *module type
       * </pre>
       */
      public Builder clearModuleType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        moduleType_ = serialization.Model.BigDLModel.ModuleType.LINEAR;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serialization.BigDLModel)
    }

    static {
      defaultInstance = new BigDLModel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.BigDLModel)
  }

  public interface BigDLTensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.BigDLTensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    java.util.List<java.lang.Integer> getSizeList();
    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    int getSizeCount();
    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    int getSize(int index);

    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    java.util.List<java.lang.Double> getDataList();
    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    int getDataCount();
    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    double getData(int index);
  }
  /**
   * Protobuf type {@code serialization.BigDLTensor}
   */
  public static final class BigDLTensor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.BigDLTensor)
      BigDLTensorOrBuilder {
    // Use BigDLTensor.newBuilder() to construct.
    private BigDLTensor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BigDLTensor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BigDLTensor defaultInstance;
    public static BigDLTensor getDefaultInstance() {
      return defaultInstance;
    }

    public BigDLTensor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BigDLTensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                size_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              size_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                size_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                size_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          size_ = java.util.Collections.unmodifiableList(size_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serialization.Model.internal_static_serialization_BigDLTensor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serialization.Model.internal_static_serialization_BigDLTensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serialization.Model.BigDLTensor.class, serialization.Model.BigDLTensor.Builder.class);
    }

    public static com.google.protobuf.Parser<BigDLTensor> PARSER =
        new com.google.protobuf.AbstractParser<BigDLTensor>() {
      public BigDLTensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BigDLTensor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BigDLTensor> getParserForType() {
      return PARSER;
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> size_;
    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getSizeList() {
      return size_;
    }
    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    public int getSizeCount() {
      return size_.size();
    }
    /**
     * <code>repeated int32 size = 1;</code>
     *
     * <pre>
     *size of tensor
     * </pre>
     */
    public int getSize(int index) {
      return size_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> data_;
    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    public java.util.List<java.lang.Double>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated double data = 2;</code>
     *
     * <pre>
     *tensor element
     * </pre>
     */
    public double getData(int index) {
      return data_.get(index);
    }

    private void initFields() {
      size_ = java.util.Collections.emptyList();
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < size_.size(); i++) {
        output.writeInt32(1, size_.get(i));
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeDouble(2, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < size_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(size_.get(i));
        }
        size += dataSize;
        size += 1 * getSizeList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDataList().size();
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serialization.Model.BigDLTensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Model.BigDLTensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Model.BigDLTensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.Model.BigDLTensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.Model.BigDLTensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Model.BigDLTensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serialization.Model.BigDLTensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serialization.Model.BigDLTensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serialization.Model.BigDLTensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serialization.Model.BigDLTensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serialization.Model.BigDLTensor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.BigDLTensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.BigDLTensor)
        serialization.Model.BigDLTensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serialization.Model.internal_static_serialization_BigDLTensor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serialization.Model.internal_static_serialization_BigDLTensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serialization.Model.BigDLTensor.class, serialization.Model.BigDLTensor.Builder.class);
      }

      // Construct using serialization.Model.BigDLTensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serialization.Model.internal_static_serialization_BigDLTensor_descriptor;
      }

      public serialization.Model.BigDLTensor getDefaultInstanceForType() {
        return serialization.Model.BigDLTensor.getDefaultInstance();
      }

      public serialization.Model.BigDLTensor build() {
        serialization.Model.BigDLTensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serialization.Model.BigDLTensor buildPartial() {
        serialization.Model.BigDLTensor result = new serialization.Model.BigDLTensor(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size_ = java.util.Collections.unmodifiableList(size_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serialization.Model.BigDLTensor) {
          return mergeFrom((serialization.Model.BigDLTensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serialization.Model.BigDLTensor other) {
        if (other == serialization.Model.BigDLTensor.getDefaultInstance()) return this;
        if (!other.size_.isEmpty()) {
          if (size_.isEmpty()) {
            size_ = other.size_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSizeIsMutable();
            size_.addAll(other.size_);
          }
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serialization.Model.BigDLTensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serialization.Model.BigDLTensor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> size_ = java.util.Collections.emptyList();
      private void ensureSizeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          size_ = new java.util.ArrayList<java.lang.Integer>(size_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getSizeList() {
        return java.util.Collections.unmodifiableList(size_);
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public int getSizeCount() {
        return size_.size();
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public int getSize(int index) {
        return size_.get(index);
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public Builder setSize(
          int index, int value) {
        ensureSizeIsMutable();
        size_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public Builder addSize(int value) {
        ensureSizeIsMutable();
        size_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public Builder addAllSize(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, size_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 size = 1;</code>
       *
       * <pre>
       *size of tensor
       * </pre>
       */
      public Builder clearSize() {
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<java.lang.Double>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public java.util.List<java.lang.Double>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public double getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public Builder setData(
          int index, double value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public Builder addData(double value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       *
       * <pre>
       *tensor element
       * </pre>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serialization.BigDLTensor)
    }

    static {
      defaultInstance = new BigDLTensor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.BigDLTensor)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_BigDLModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_BigDLModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_BigDLTensor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_BigDLTensor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\rserialization\"\270\002\n\nBigDLMo" +
      "del\022\014\n\004name\030\001 \001(\t\022-\n\nsubModules\030\002 \003(\0132\031." +
      "serialization.BigDLModel\022*\n\006weight\030\003 \001(\013" +
      "2\032.serialization.BigDLTensor\022(\n\004bias\030\004 \001" +
      "(\0132\032.serialization.BigDLTensor\022\024\n\014module" +
      "Params\030\005 \003(\001\022\014\n\004tops\030\006 \003(\t\022\017\n\007bottoms\030\007 " +
      "\003(\t\0228\n\nmoduleType\030\010 \002(\0162$.serialization." +
      "BigDLModel.ModuleType\"(\n\nModuleType\022\n\n\006L" +
      "INEAR\020\001\022\016\n\nSEQUENTIAL\020\002\")\n\013BigDLTensor\022\014" +
      "\n\004size\030\001 \003(\005\022\014\n\004data\030\002 \003(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serialization_BigDLModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serialization_BigDLModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_BigDLModel_descriptor,
        new java.lang.String[] { "Name", "SubModules", "Weight", "Bias", "ModuleParams", "Tops", "Bottoms", "ModuleType", });
    internal_static_serialization_BigDLTensor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serialization_BigDLTensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_BigDLTensor_descriptor,
        new java.lang.String[] { "Size", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
